import debug from 'debug';
import { Command } from './command.js';

const log = debug(`Anime`);

export class Anime extends Command {
  constructor(client) {
    super(client);

    this.responses = [
		'Hirasawa Yui! http://cdn.myanimelist.net/images/characters/11/48457.jpg',
'The best anime is Akiyama Mio! http://cdn.myanimelist.net/images/characters/12/51295.jpg',
'The best anime is Kotobuki Tsumugi! http://cdn.myanimelist.net/images/characters/8/51210.jpg',
'The best anime is Nakano Azusa! http://cdn.myanimelist.net/images/characters/10/84890.jpg',
'The best anime is Suzuki Jun! http://cdn.myanimelist.net/images/characters/3/95854.jpg',
'The best anime is Hirasawa Ui! http://cdn.myanimelist.net/images/characters/14/48575.jpg',
'The best anime is Saitō Sumire! http://cdn.myanimelist.net/images/characters/6/181351.jpg',
'The best anime is Okuda Nao! http://cdn.myanimelist.net/images/characters/10/117658.jpg',
'The best anime is Yamanaka Sawako! http://cdn.myanimelist.net/images/characters/14/48577.jpg',
'The best anime is Manabe Nodoka! http://cdn.myanimelist.net/images/characters/15/80300.jpg',
'The best anime is Tainaka Satoshi! http://cdn.myanimelist.net/images/characters/16/83873.jpg',
'The best anime is Ton-chan!',
'The best anime is the Occult Club Members!',
'The best anime is Izumi Konata! http://cdn.myanimelist.net/images/characters/15/53298.jpg',
'The best anime is Hiiragi Kagami! http://cdn.myanimelist.net/images/characters/10/40319.jpg',
'The best anime is Hiiragi Tsukasa! http://cdn.myanimelist.net/images/characters/10/78780.jpg',
'The best anime is Takara Miyuki! http://cdn.myanimelist.net/images/characters/7/80556.jpg',
'The best anime is Patricia Martin! http://cdn.myanimelist.net/images/characters/15/260277.jpg',
'The best anime is Itoshiki Nozomu! http://cdn.myanimelist.net/images/characters/14/36021.jpg',
'The best anime is Itoshiki Rin! http://cdn.myanimelist.net/images/characters/2/50109.jpg',
'The best anime is Fuura Kafuka! http://cdn.myanimelist.net/images/characters/11/30372.jpg',
'The best anime is Kitsu Chiri! http://cdn.myanimelist.net/images/characters/10/246635.jpg',
'The best anime is Kobushi Abiru! http://cdn.myanimelist.net/images/characters/12/111356.jpg',
'The best anime is Komori Kiri! http://cdn.myanimelist.net/images/characters/11/80136.jpg',
'The best anime is Tsunetsuki Matoi! http://cdn.myanimelist.net/images/characters/8/50116.jpg',
'The best anime is Hitō Nami! http://cdn.myanimelist.net/images/characters/6/36026.jpg',
'The best anime is Fujiyoshi Harumi! http://cdn.myanimelist.net/images/characters/9/36022.jpg',
'The best anime is Sekiutsu Maria Taro! http://cdn.myanimelist.net/images/characters/13/50135.jpg',
'The best anime is Otonashi Meru! http://cdn.myanimelist.net/images/characters/13/50124.jpg',
'The best anime is Kimura Kaere! http://cdn.myanimelist.net/images/characters/2/50111.jpg',
'The best anime is Kimura Kaede! http://cdn.myanimelist.net/images/characters/2/50111.jpg',
'The best anime is Kyuubey! http://cdn.myanimelist.net/images/characters/12/123391.jpg',
'The best anime is qb! http://cdn.myanimelist.net/images/characters/12/123387.jpg',
'The best anime is Akemi Homura! http://cdn.myanimelist.net/images/characters/16/219769.jpg',
'The best anime is Kaname Madoka! http://cdn.myanimelist.net/images/characters/3/243537.jpg',
'The best anime is Sayaka Miki! http://cdn.myanimelist.net/images/characters/13/107672.jpg',
'The best anime is Sakura Kyouko! http://cdn.myanimelist.net/images/characters/13/123397.jpg',
'The best anime is Tomoe Mami! http://cdn.myanimelist.net/images/characters/9/122437.jpg',
'The best anime is Kamijou Kyousuke! http://cdn.myanimelist.net/images/characters/2/114694.jpg',
'The best anime is Shizuki Hitomi! http://cdn.myanimelist.net/images/characters/7/108840.jpg',
'The best anime is Ichii Tooru! http://cdn.myanimelist.net/images/characters/2/114814.jpg',
'The best anime is Momoki Run! http://cdn.myanimelist.net/images/characters/13/119577.jpg',
'The best anime is Nishi Yuuko! http://cdn.myanimelist.net/images/characters/13/113049.jpg',
'The best anime is Tennouji Nagisa! http://cdn.myanimelist.net/images/characters/6/114849.jpg',
'The best anime is Araragi Koyomi! http://cdn.myanimelist.net/images/characters/3/148437.jpg',
'The best anime is Hanekawa Tsubasa! http://cdn.myanimelist.net/images/characters/7/105363.jpg',
'The best anime is Senjougahara Hitagi! http://cdn.myanimelist.net/images/characters/4/66188.jpg',
'The best anime is Araragi Karen! http://cdn.myanimelist.net/images/characters/11/146639.jpg',
'The best anime is Araragi Tsukihi! http://cdn.myanimelist.net/images/characters/6/146641.jpg',
'The best anime is Hachikuji Mayoi! http://cdn.myanimelist.net/images/characters/3/154457.jpg',
'The best anime is Kanbaru Suruga! http://cdn.myanimelist.net/images/characters/11/222449.jpg',
'The best anime is Oshino Meme! http://cdn.myanimelist.net/images/characters/14/148439.jpg',
'The best anime is Oshino Ougi! http://cdn.myanimelist.net/images/characters/12/227559.jpg',
'The best anime is Sengoku Nadeko! http://cdn.myanimelist.net/images/characters/10/85614.jpg',
'The best anime is Oshino Shiobu! http://cdn.myanimelist.net/images/characters/16/234167.jpg',
'The best anime is Kuroi Mato! http://cdn.myanimelist.net/images/characters/5/168239.jpg',
'The best anime is Takanashi Yomi! http://cdn.myanimelist.net/images/characters/5/210495.jpg',
'The best anime is Ayanami Rei! http://cdn.myanimelist.net/images/characters/8/78732.jpg',
'The best anime is (not) Ikari Shinji! http://cdn.myanimelist.net/images/characters/5/78734.jpg',
'The best anime is Katsuragi Misato! http://cdn.myanimelist.net/images/characters/16/209971.jpg',
'The best anime is Pen Pen! http://cdn.myanimelist.net/images/characters/15/88929.jpg',
'The best anime is Akagi Ritsuko! http://cdn.myanimelist.net/images/characters/3/62447.jpg',
'The best anime is Fuyutsuki Kohzou! http://cdn.myanimelist.net/images/characters/10/145223.jpg',
'The best anime is Ikari Gendo! http://cdn.myanimelist.net/images/characters/11/53131.jpg',
'The best anime is Nagisa Kaworu! http://cdn.myanimelist.net/images/characters/3/175413.jpg',
'The best anime is Asuka Langley Soryu! http://cdn.myanimelist.net/images/characters/12/79465.jpg',
'The best anime is Mari Makinami Illustrious! http://cdn.myanimelist.net/images/characters/6/131325.jpg',
'The best anime is Amatsuka Mao! http://cdn.myanimelist.net/images/characters/5/192753.jpg',
'The best anime is Amatsuka Megumi! http://cdn.myanimelist.net/images/characters/4/192751.jpg',
'The best anime is Kirara Bernstein! http://cdn.myanimelist.net/images/characters/15/192749.jpg',
'The best anime is definitely not Kannazuki Tamaki! http://cdn.myanimelist.net/images/characters/11/199423.jpg',
'The best anime is Shinomiya Kyouya! http://cdn.myanimelist.net/images/characters/16/192747.jpg',
'The best anime is Sumeragi Shion! http://cdn.myanimelist.net/images/characters/16/192745.jpg',
'The best anime is Haruhara Haruko! http://cdn.myanimelist.net/images/characters/16/33202.jpg',
'The best anime is Nandaba Naota! http://cdn.myanimelist.net/images/characters/12/117021.jpg',
'The best anime is Samejima Mamimi! http://cdn.myanimelist.net/images/characters/13/166079.jpg',
'The best anime is Canti! http://cdn.myanimelist.net/images/characters/2/33205.jpg',
'The best anime is Ninamori Eri! http://cdn.myanimelist.net/images/characters/16/94555.jpg',
'The best anime is YUNO WHO IT IS (X `_______` )',
'The best anime is Yuno! http://cdn.myanimelist.net/images/characters/15/27660.jpg',
'The best anime is Miyako! http://cdn.myanimelist.net/images/characters/15/164295.jpg',
'The best anime is Sae! http://cdn.myanimelist.net/images/characters/16/38859.jpg',
'The best anime is Hiro! http://cdn.myanimelist.net/images/characters/15/38858.jpg',
'The best anime is Yoshinoya-sensei! http://cdn.myanimelist.net/images/characters/9/206709.jpg',
'The best anime is Ana Coppola! http://cdn.myanimelist.net/images/characters/10/78044.jpg',
'The best anime is Itou Chika! http://cdn.myanimelist.net/images/characters/12/38348.jpg',
'The best anime is Itou Nobue! http://cdn.myanimelist.net/images/characters/14/38346.jpg',
'The best anime is Matsuoka Miu! http://cdn.myanimelist.net/images/characters/16/38347.jpg',
'The best anime is Sakuragi Matsuri! http://cdn.myanimelist.net/images/characters/10/82296.jpg',
'The best anime is Inferno Cop! http://cdn.myanimelist.net/images/characters/4/197629.jpg',
'The best anime is Watashi (female)! http://cdn.myanimelist.net/images/characters/9/173179.jpg',
'The best anime is Watashi (male)! http://cdn.myanimelist.net/images/characters/11/89099.jpg',
'The best anime is Y! http://cdn.myanimelist.net/images/characters/13/173223.jpg',
'The best anime is Iggy! http://cdn.myanimelist.net/images/characters/2/133145.jpg',
'The best anime is Mohammed Avdol! http://cdn.myanimelist.net/images/characters/6/242477.jpg',
'The best anime is Dio Brando! http://cdn.myanimelist.net/images/characters/10/252875.jpg',
'The best anime is Joseph Joestar! http://cdn.myanimelist.net/images/characters/3/203297.jpg',
'The best anime is Noriaki Kakyoin! http://cdn.myanimelist.net/images/characters/8/245201.jpg',
'The best anime is Jotaro Kujo! http://cdn.myanimelist.net/images/characters/9/245211.jpg',
'The best anime is Jean-Pierre Polnareff! http://cdn.myanimelist.net/images/characters/10/245195.jpg',
'The best anime is Robert E.O. Speedwagon! http://cdn.myanimelist.net/images/characters/14/240197.jpg',
'The best anime is Jonathan Joestar! http://cdn.myanimelist.net/images/characters/10/182715.jpg',
'The best anime is William Anthonio Zeppeli! http://cdn.myanimelist.net/images/characters/12/251685.jpg',
'The best anime is Caesar Anthonio Zeppeli! http://cdn.myanimelist.net/images/characters/11/190474.jpg',
'The best anime is Sonya-chan! http://cdn.myanimelist.net/images/characters/13/153367.jpg',
'The best anime is Goshiki Agiri! http://cdn.myanimelist.net/images/characters/14/150141.jpg',
'The best anime is Oribe Yasuna! http://cdn.myanimelist.net/images/characters/12/150671.jpg',
'The best anime is Kaiki Deishu! http://cdn.myanimelist.net/images/characters/9/258299.jpg',
'The best anime is Kaiki Deishu! http://cdn.myanimelist.net/images/characters/9/258299.jpg',
'The best anime is Kaiki Deishu! http://cdn.myanimelist.net/images/characters/9/258299.jpg',
'The best anime is Takakura Himari! http://cdn.myanimelist.net/images/characters/6/124891.jpg',
'The best anime is Oginome Ringo! http://cdn.myanimelist.net/images/characters/5/134121.jpg',
'The best anime is Takakura Kanba! http://cdn.myanimelist.net/images/characters/3/121976.jpg',
'The best anime is Takakura Shouma! http://cdn.myanimelist.net/images/characters/12/127533.jpg',
'The best anime is Anrakutei Kukuru! http://cdn.myanimelist.net/images/characters/4/177701.jpg',
'The best anime is Bouhatei Tetora! http://cdn.myanimelist.net/images/characters/12/173559.jpg',
'The best anime is Buratei Marii! http://cdn.myanimelist.net/images/characters/13/174719.jpg',
'The best anime is Haroukitei Kigurumi! http://cdn.myanimelist.net/images/characters/5/177655.jpg',
'The best anime is Kuurubiyuutei Gankyou! http://cdn.myanimelist.net/images/characters/13/149113.jpg',
'The best anime is Sakamoto-san! http://cdn.myanimelist.net/images/characters/12/113323.jpg',
'The best anime is Aioi Yuuko! http://cdn.myanimelist.net/images/characters/12/114021.jpg',
'The best anime is Minakami Mai! http://cdn.myanimelist.net/images/characters/3/114022.jpg',
'The best anime is Naganohara Mio! http://cdn.myanimelist.net/images/characters/2/112674.jpg',
'The best anime is Shinonome Nano! http://cdn.myanimelist.net/images/characters/11/112682.jpg',
'The best anime is Shinonome Hakase! http://cdn.myanimelist.net/images/characters/15/117568.jpg',
'The best anime is Annaka haruna? ええええええええええ？ http://cdn.myanimelist.net/images/characters/13/118442.jpg',
'The best anime is Pino! http://cdn.myanimelist.net/images/characters/8/117696.jpg',
'The best anime is Tachibana Misato! http://cdn.myanimelist.net/images/characters/15/117591.jpg',
'The best anime is Miyauchi Renge! http://cdn.myanimelist.net/images/characters/4/225023.jpg',
'The best anime is Koshigaya Komari! http://cdn.myanimelist.net/images/characters/3/225067.jpg',
'The best anime is Koshigaya Natsumi! http://cdn.myanimelist.net/images/characters/14/222841.jpg',
'The best anime is Ichijou Hotaru! http://cdn.myanimelist.net/images/characters/15/222839.jpg',
'The best anime is Kousaka Kyousuke! http://cdn.myanimelist.net/images/characters/9/103693.jpg',
'The best anime is Kousaka Kirino! http://cdn.myanimelist.net/images/characters/4/71166.jpg',
'The best anime is Aragaki Ayase! http://cdn.myanimelist.net/images/characters/14/102465.jpg',
'The best anime is Gokou Ruri! http://cdn.myanimelist.net/images/characters/9/101412.jpg',
'The best anime is Garterbelt! http://cdn.myanimelist.net/images/characters/11/99525.jpg',
'The best anime is Panty! http://cdn.myanimelist.net/images/characters/3/101483.jpg',
'The best anime is Stocking! http://cdn.myanimelist.net/images/characters/8/101434.jpg',
'The best anime is Scanty! http://cdn.myanimelist.net/images/characters/4/159147.jpg',
'The best anime is Kneesocks! http://cdn.myanimelist.net/images/characters/4/159167.jpg',
'The best anime is Kazanari Tsubasa! http://cdn.myanimelist.net/images/characters/15/205629.jpg',
'The best anime is Tachibana Hibiki! http://cdn.myanimelist.net/images/characters/13/159127.jpg',
'The best anime is Yukine Chris! http://cdn.myanimelist.net/images/characters/4/222307.jpg',
'The best anime is Ika Musume! http://cdn.myanimelist.net/images/characters/12/105105.jpg',
'The best anime is Aizawa Eiko! http://cdn.myanimelist.net/images/characters/16/103207.jpg',
'The best anime is Aizawa Chizuru! http://cdn.myanimelist.net/images/characters/4/105119.jpg',
'The best anime is Hashida Itaru! http://cdn.myanimelist.net/images/characters/6/113767.jpg',
'The best anime is Makise Kurisu! http://cdn.myanimelist.net/images/characters/11/113023.jpg',
'The best anime is Okabe Rintarou! http://cdn.myanimelist.net/images/characters/6/122643.jpg',
'The best anime is Kyouma Houhouin! http://cdn.myanimelist.net/images/characters/11/241541.jpg',
'The best anime is Shiina Mayuri! http://cdn.myanimelist.net/images/characters/10/119651.jpg',
'The best anime is Akiha Rumiho! http://cdn.myanimelist.net/images/characters/8/113021.jpg',
'The best anime is Amane Suzuha! http://cdn.myanimelist.net/images/characters/14/122639.jpg',
'The best anime is Kiryuu Moeka! http://cdn.myanimelist.net/images/characters/5/122645.jpg',
'The best anime is Urushibara Ruka! http://cdn.myanimelist.net/images/characters/7/133805.jpg',
'The best anime is Hercule Barton! http://cdn.myanimelist.net/images/characters/11/209741.jpg',
'The best anime is Cordelia Glauca! http://cdn.myanimelist.net/images/characters/15/209739.jpg',
'The best anime is Sherlock Shellingford! http://cdn.myanimelist.net/images/characters/5/150781.jpg',
'The best anime is Semen Demon! http://cdn.myanimelist.net/images/characters/5/150781.jpg',
'The best anime is Yuzurizaki Nero! http://cdn.myanimelist.net/images/characters/14/103411.jpg',
'The best anime is Akechi Kokoro! http://cdn.myanimelist.net/images/characters/15/106088.jpg',
'The best anime is Misaka Mikoto! http://cdn.myanimelist.net/images/characters/3/78211.jpg',
'The best anime is Biribiri! http://cdn.myanimelist.net/images/characters/3/78211.jpg',
'The best anime is definitely not Saten Ruiko! http://cdn.myanimelist.net/images/characters/3/225857.jpg',
'The best anime is Shirai Kuroko! http://cdn.myanimelist.net/images/characters/3/78213.jpg',
'The best anime is Uiharu Kazari! http://cdn.myanimelist.net/images/characters/3/65711.jpg',
'The best anime is Accelerator! http://cdn.myanimelist.net/images/characters/3/229939.jpg',
'The best anime is Kamijou "The Touman" Touma! http://cdn.myanimelist.net/images/characters/14/33865.jpg',
'The best anime is definitely not Index Librorum Prohibitorum! http://cdn.myanimelist.net/images/characters/10/33864.jpg',
'The best anime is Misaka imouto! http://cdn.myanimelist.net/images/characters/2/73911.jpg',
'The best anime is Kyon! http://cdn.myanimelist.net/images/characters/13/75369.jpg',
'The best anime is Nagato Yuki! http://cdn.myanimelist.net/images/characters/10/78722.jpg',
'The best anime is Tsuruya! http://cdn.myanimelist.net/images/characters/10/82450.jpg',
'The best anime is Kyon`s sister! きょんくんでんわー http://cdn.myanimelist.net/images/characters/7/93967.jpg',
'The best anime is Mikuru Asahina! http://cdn.myanimelist.net/images/characters/9/75525.jpg',
'The best anime is Asakura Ryouko! http://cdn.myanimelist.net/images/characters/7/89053.jpg',
'The best anime is Koizumi Itsuki! http://cdn.myanimelist.net/images/characters/14/75055.jpg',
'The best anime is Suzumiya Haruhi! http://cdn.myanimelist.net/images/characters/12/69815.jpg',
'The best anime is Futaba Aoi! http://cdn.myanimelist.net/images/characters/2/177389.jpg',
'The best anime is Isshiki Akane! http://cdn.myanimelist.net/images/characters/4/177387.jpg',
'The best anime is Kuroki Rei! http://cdn.myanimelist.net/images/characters/2/193267.jpg',
'The best anime is Saegusa Wakaba! http://cdn.myanimelist.net/images/characters/7/194945.jpg',
'The best anime is Shinomiya Himawari http://cdn.myanimelist.net/images/characters/3/195077.jpg',
'The best anime is Akashi http://cdn.myanimelist.net/images/characters/15/89098.jpg',
'The best anime is Ozu! http://cdn.myanimelist.net/images/characters/13/89632.jpg',
'The best anime is Akaza Akari!　＼アッカリーン~／ http://i.imgur.com/LJ4zX6l.png',
'The best anime is Funami Yui! http://cdn.myanimelist.net/images/characters/16/116745.jpg',
'The best anime is KYOUKO TOSHINO! http://cdn.myanimelist.net/images/characters/5/116751.jpg',
'The best anime is Yoshikawa Chinatsu! http://cdn.myanimelist.net/images/characters/14/116763.jpg',
'The best anime is Furutani Himawari! http://cdn.myanimelist.net/images/characters/13/134009.jpg',
'The best anime is Ikeda Chitose! http://cdn.myanimelist.net/images/characters/10/116765.jpg',
'The best anime is Ikeda Chizuru! http://cdn.myanimelist.net/images/characters/15/131047.jpg',
'The best anime is Ohmuro Sakurako! http://cdn.myanimelist.net/images/characters/6/134011.jpg',
'The best anime is Sugiura Ayano! http://cdn.myanimelist.net/images/characters/14/116768.jpg',
'The best anime is Hinata Yukari! http://cdn.myanimelist.net/images/characters/6/203493.jpg',
'The best anime is Ichii Yui! http://cdn.myanimelist.net/images/characters/16/205915.jpg',
'The best anime is Nonohara Yuzuko! http://cdn.myanimelist.net/images/characters/9/203489.jpg',
'The best anime is Matsumoto Yoriko! http://cdn.myanimelist.net/images/characters/8/203495.jpg',
'The best anime is Lynette Bishop! http://cdn.myanimelist.net/images/characters/5/51297.jpg',
'The best anime is Perrine H. Clostermann! http://cdn.myanimelist.net/images/characters/16/51298.jpg',
'The best anime is Miyafuji Yoshika! http://cdn.myanimelist.net/images/characters/16/51296.jpg',
'The best anime is Sakamoto Mio! http://cdn.myanimelist.net/images/characters/8/137395.jpg',
'The best anime is Minna-Dietlinde Wilcke! http://cdn.myanimelist.net/images/characters/6/51300.jpg',
'The best anime is Gertrud Barkhorn! http://cdn.myanimelist.net/images/characters/16/51301.jpg',
'The best anime is Hartmann Erica! http://cdn.myanimelist.net/images/characters/2/51302.jpg',
'The best anime is Eila Ilmatar Juutilainen! http://cdn.myanimelist.net/images/characters/10/51306.jpg',
'The best anime is Sanya V. Litvyak! http://cdn.myanimelist.net/images/characters/14/172975.jpg',
'The best anime is Francesca Lucchini! http://cdn.myanimelist.net/images/characters/13/51304.jpg',
'The best anime is Charlotte E. Yeager! http://cdn.myanimelist.net/images/characters/12/51303.jpg',
'The best anime is Ononoki Yotsugi! http://cdn.myanimelist.net/images/characters/9/230189.jpg',
'The best anime is Ooyama Tochiro! http://cdn.myanimelist.net/images/characters/7/104028.jpg',
'The best anime is Phantom Harlock! http://cdn.myanimelist.net/images/characters/3/100311.jpg',
'The best anime is Dan Eagleman! http://cdn.myanimelist.net/images/characters/5/143713.jpg',
'The best anime is Kagura! http://cdn.myanimelist.net/images/characters/4/48177.jpg',
'The best anime is Kasuga Ayumu! http://cdn.myanimelist.net/images/characters/3/27890.jpg',
'The best anime is Mihama Chiyo! http://cdn.myanimelist.net/images/characters/13/35084.jpg',
'The best anime is Mizuhara Koyomi! http://cdn.myanimelist.net/images/characters/2/56154.jpg',
'The best anime is Sakaki! http://cdn.myanimelist.net/images/characters/14/56155.jpg',
'The best anime is Takino Tomo! http://cdn.myanimelist.net/images/characters/9/48176.jpg',
'The best anime is Tanizaki Yukari! http://cdn.myanimelist.net/images/characters/3/254819.jpg',
'The best anime is Kimura-sensei! http://cdn.myanimelist.net/images/characters/6/75243.jpg',
'The best anime is Kaorin! http://cdn.myanimelist.net/images/characters/6/115358.jpg',
'The best anime is Chiyo`s father! http://cdn.myanimelist.net/images/voiceactors/1/14319.jpg',
'The best anime is Kurosawa Minamo! http://cdn.myanimelist.net/images/characters/2/254985.jpg',
'The best anime is Senketsu! http://cdn.myanimelist.net/images/characters/5/224171.jpg',
'The best anime is Kiryuuin Satsuki! http://cdn.myanimelist.net/images/characters/3/231163.jpg',
'The best anime is Mankanshoku Mako! http://cdn.myanimelist.net/images/characters/9/232905.jpg',
'The best anime is Matoi Ryuuko! http://cdn.myanimelist.net/images/characters/6/240227.jpg',
'The best anime is Gamagoori Ira! http://cdn.myanimelist.net/images/characters/7/217771.jpg',
'The best anime is Harime Nui! http://cdn.myanimelist.net/images/characters/7/229073.jpg',
'The best anime is Inumuta Houka! http://cdn.myanimelist.net/images/characters/6/217767.jpg',
'The best anime is Jakuzure Nonon! http://cdn.myanimelist.net/images/characters/2/217769.jpg',
'The best anime is Mikisugi Aikurou! http://cdn.myanimelist.net/images/characters/13/223777.jpg',
'The best anime is Sanageyama Uzu! http://cdn.myanimelist.net/images/characters/5/234905.jpg',
'The best anime is Ichijou Raku! http://cdn.myanimelist.net/images/characters/12/242215.jpg',
'The best anime is Kirisaki Chitoge! http://cdn.myanimelist.net/images/characters/7/241651.jpg',
'The best anime is Onodera Kosaki! http://cdn.myanimelist.net/images/characters/9/241653.jpg',
'The best anime is Miyamoto Ruri! http://cdn.myanimelist.net/images/characters/9/235033.jpg',
'The best anime is Dandy! http://cdn.myanimelist.net/images/characters/7/231179.jpg',
'The best anime is QT! http://cdn.myanimelist.net/images/characters/16/231175.jpg',
'The best anime is Katsura Hinagiku! http://cdn.myanimelist.net/images/characters/3/116216.jpg',
'The best anime is Hatsune Miku! http://i.imgur.com/yVLuoGh.png',
'The best anime is Hinamori Amu! http://cdn.myanimelist.net/images/characters/4/38549.jpg',
'The best anime is ',
'The best anime is Kurapika! http://cdn.myanimelist.net/images/characters/4/174563.jpg',
'The best anime is Gon Freecss! http://cdn.myanimelist.net/images/characters/15/205443.jpg',
'The best anime is Leorio Paladiknight! http://cdn.myanimelist.net/images/characters/11/174519.jpg',
'The best anime is Killua Zoldyck! http://cdn.myanimelist.net/images/characters/9/174559.jpg',
'The best anime is Hisoka! http://cdn.myanimelist.net/images/characters/3/174561.jpg',
'The best anime is Neferpitou! http://cdn.myanimelist.net/images/characters/14/236791.jpg',
'The best anime is Netero Isaac! http://cdn.myanimelist.net/images/characters/12/244127.jpg',
'The best anime is Bandou Marimo! http://cdn.myanimelist.net/images/characters/6/190192.jpg',
'The best anime is Bandou Marimo! http://cdn.myanimelist.net/images/characters/6/190192.jpg',
'The best anime is Oshimoto Yuri! http://cdn.myanimelist.net/images/characters/10/190198.jpg',
'The best anime is Shinjou Kanae! http://cdn.myanimelist.net/images/characters/9/184977.jpg',
'The best anime is Takamiya Nasuno! http://cdn.myanimelist.net/images/characters/16/190194.jpg',
'The best anime is Kagami Sumika! http://cdn.myanimelist.net/images/characters/11/136441.jpg',
'The best anime is Mitsurugi Meiya! http://cdn.myanimelist.net/images/characters/10/202421.jpg',
'The best anime is Onodera Punpun! http://cdn.myanimelist.net/images/characters/11/229841.jpg',
'The best anime is Tanaka Aiko! http://cdn.myanimelist.net/images/characters/5/158639.jpg',
'The best anime is God (Oyasumi Punpun)! http://cdn.myanimelist.net/images/characters/5/216605.jpg',
'The best anime is Tsukasa! http://cdn.myanimelist.net/images/characters/3/33096.jpg',
'The best anime is Subaru! http://cdn.myanimelist.net/images/characters/14/86295.jpg',
'The best anime is Miniwa Tsumiki! http://cdn.myanimelist.net/images/characters/4/161549.jpg',
'The best anime is Haruno Hime! http://cdn.myanimelist.net/images/characters/11/161545.jpg',
'The best anime is Inui Sakaki! http://cdn.myanimelist.net/images/characters/10/171001.jpg',
'The best anime is Katase Mayoi! http://cdn.myanimelist.net/images/characters/15/170999.jpg',
'The best anime is Otonashi Io! http://cdn.myanimelist.net/images/characters/9/161507.jpg',
'The best anime is Munakata Coachy! http://cdn.myanimelist.net/images/characters/16/112320.jpg',
'The best anime is Oka Hiromi! http://cdn.myanimelist.net/images/characters/7/112321.jpg',
'The best anime is Ryuuzaki Reika! http://cdn.myanimelist.net/images/characters/8/112322.jpg',
'The best anime is TETSUOOOOOOOOOO! http://cdn.myanimelist.net/images/characters/7/30617.jpg',
'The best anime is Kaneda Shotaro! http://cdn.myanimelist.net/images/characters/2/30620.jpg',
'The best anime is Yabuki Joe! http://cdn.myanimelist.net/images/characters/2/92715.jpg',
'The best anime is Tange Danpei! http://cdn.myanimelist.net/images/characters/4/126741.jpg',
'The best anime is Hana Oshiroi! http://cdn.myanimelist.net/images/characters/14/197739.jpg',
'The best anime is Satou You! http://cdn.myanimelist.net/images/characters/16/147109.jpg',
'The best anime is Shaga Ayame! http://cdn.myanimelist.net/images/characters/9/138959.jpg',
'The best anime is Yarizui Sen! http://cdn.myanimelist.net/images/characters/16/148153.jpg',
'The best anime is Long Haired Kyou! http://cdn.myanimelist.net/images/characters/15/197705.jpg',
'The best anime is Short Haired Kyou! http://cdn.myanimelist.net/images/characters/13/197703.jpg',
'The best anime is SHIRAUME UME! http://cdn.myanimelist.net/images/characters/12/145441.jpg',
'The best anime is Binboda Momiji! http://cdn.myanimelist.net/images/characters/14/173101.jpg',
'The best anime is Sakura Ichiko! http://cdn.myanimelist.net/images/characters/15/177301.jpg',
'The best anime is Hororo! http://cdn.myanimelist.net/images/characters/6/11224.jpg',
'The best anime is Kururu! http://cdn.myanimelist.net/images/characters/14/5336.jpg',
'The best anime is Sarara! http://cdn.myanimelist.net/images/characters/3/62635.jpg',
'The best anime is Chiriri! http://cdn.myanimelist.net/images/characters/6/5338.jpg',
'The best anime is Tama-chan! http://cdn.myanimelist.net/images/characters/14/30009.jpg',
'The best anime is Maetel! http://cdn.myanimelist.net/images/characters/15/110613.jpg',
'The best anime is Kubrick Fear! http://cdn.myanimelist.net/images/characters/16/130277.jpg',
'The best anime is Muramasa Konoha! http://cdn.myanimelist.net/images/characters/6/130283.jpg',
'The best anime is Ueno Kirika! http://cdn.myanimelist.net/images/characters/10/130285.jpg',
'The best anime is Yachi Haruaki! http://cdn.myanimelist.net/images/characters/6/130287.jpg',
'The best anime is Sovereignty! http://cdn.myanimelist.net/images/characters/14/131195.jpg',
'The best anime is Amanda Carlot! http://cdn.myanimelist.net/images/characters/4/208081.jpg',
'The best anime is Aoi Sena! http://cdn.myanimelist.net/images/characters/6/28714.jpg',
'The best anime is Kishimoto Ayase! http://cdn.myanimelist.net/images/characters/10/54186.jpg',
'The best anime is Kusunoki Yua! http://cdn.myanimelist.net/images/characters/3/28715.jpg',
'The best anime is Nishijou Nanami! http://cdn.myanimelist.net/images/characters/4/34519.jpg',
'The best anime is Nishijou Takumi! http://cdn.myanimelist.net/images/characters/5/35602.jpg',
'The best anime is Orihara Kozue! http://cdn.myanimelist.net/images/characters/7/28718.jpg',
'The best anime is Sakihata Rimi! http://cdn.myanimelist.net/images/characters/14/77810.jpg',
'The best anime is fun^10xint^40=Ir2',
'The best anime is Motosuwa Hideki! http://cdn.myanimelist.net/images/characters/4/44770.jpg',
'The best anime is Chii! http://cdn.myanimelist.net/images/characters/9/251407.jpg',
'The best anime is Tadakuni! http://cdn.myanimelist.net/images/characters/13/150423.jpg',
'The best anime is Ringo-chan! http://cdn.myanimelist.net/images/characters/5/166579.jpg',
'The best anime is Ren Ren Ren Nagusaran Rensia Ruroonren Nakora! http://cdn.myanimelist.net/images/characters/7/19108.jpg',
'The best anime is Thanast Useim Ruki Miu Sia Nostal Ren Naguregyug! http://cdn.myanimelist.net/images/characters/5/44721.jpg',
'The best anime is Touwa Erio! http://cdn.myanimelist.net/images/characters/16/148145.jpg',
'The best anime is Niwa Makoto! http://cdn.myanimelist.net/images/characters/16/117809.jpg',
'The best anime is Mifune Ryuuko! http://cdn.myanimelist.net/images/characters/3/114673.jpg',
'The best anime is Maekawa! http://cdn.myanimelist.net/images/characters/13/114671.jpg',
'The best anime is Hoshimiya Yashiro! http://cdn.myanimelist.net/images/characters/12/123307.jpg',
'The best anime is Touwa Meme! http://cdn.myanimelist.net/images/characters/10/114383.jpg',
'The best anime is Juuzawa Juu! http://cdn.myanimelist.net/images/characters/16/108791.jpg',
'The best anime is Ochibana Ame! http://cdn.myanimelist.net/images/characters/10/73497.jpg',
'The best anime is Dejiko! http://cdn.myanimelist.net/images/characters/11/60826.jpg',
'The best anime is Puchiko! http://cdn.myanimelist.net/images/characters/15/60825.jpg',
'The best anime is Usada Hikaru! http://cdn.myanimelist.net/images/characters/12/104416.jpg',
'The best anime is Orihara Izaya! http://cdn.myanimelist.net/images/characters/2/234913.jpg',
'The best anime is Celty! http://cdn.myanimelist.net/images/characters/5/81495.jpg',
'The best anime is Sonohara Anri! http://cdn.myanimelist.net/images/characters/12/87011.jpg',
'The best anime is Kida Masaomi! http://cdn.myanimelist.net/images/characters/9/97698.jpg',
'The best anime is Ryuugamine Mikado! http://cdn.myanimelist.net/images/characters/13/76261.jpg',
'The best anime is Heiwajima Shizuo! http://cdn.myanimelist.net/images/characters/9/76252.jpg',
'The best anime is Kishitani Shinra! http://cdn.myanimelist.net/images/characters/2/84118.jpg',
'The best anime is Amamiya Yuuko! http://cdn.myanimelist.net/images/characters/9/34430.jpg',
'The best anime is Shindou Chihiro! http://cdn.myanimelist.net/images/characters/8/38933.jpg',
'The best anime is Blanket Arrester! http://cdn.myanimelist.net/images/characters/4/42838.jpg',
'The best anime is Cryostat Plug! http://cdn.myanimelist.net/images/characters/15/42837.jpg',
'The best anime is Rentarou Futaba! http://cdn.myanimelist.net/images/characters/13/51591.jpg',
'The best anime is Shirogane Sara! http://cdn.myanimelist.net/images/characters/15/44888.jpg',
'The best anime is Shirogane Souju! http://cdn.myanimelist.net/images/characters/16/52184.jpg',
'The best anime is IKAFIRE! http://cdn.myanimelist.net/images/characters/16/204445.jpg',
'The best anime is Chigusa Ui! http://cdn.myanimelist.net/images/characters/4/52168.jpg',
'The best anime is Chigusa Koi! http://cdn.myanimelist.net/images/characters/6/52169.jpg',
'The best anime is Hariyama Nishimori! http://cdn.myanimelist.net/images/characters/7/58663.jpg',
'The best anime is Hinagiku Lala! http://cdn.myanimelist.net/images/characters/2/52170.jpg',
'The best anime is Hinagiku Lulu! http://cdn.myanimelist.net/images/characters/8/52171.jpg',
'The best anime is Ichijou Sumireko! http://cdn.myanimelist.net/images/characters/8/52188.jpg',
'The best anime is Ichijou Kaoruko! http://cdn.myanimelist.net/images/characters/5/52189.jpg',
'The best anime is Momoi Ai! http://cdn.myanimelist.net/images/characters/15/52172.jpg',
'The best anime is Momoi Mai! http://cdn.myanimelist.net/images/characters/7/52418.jpg',
'The best anime is Sakurazuki Yura! http://cdn.myanimelist.net/images/characters/4/52187.jpg',
'The best anime is Sakurazuki Kira! http://cdn.myanimelist.net/images/characters/5/52186.jpg',
'The best anime is Hoshikawa Seira! http://cdn.myanimelist.net/images/characters/11/213471.jpg',
'The best anime is Shirokane Ginka! http://cdn.myanimelist.net/images/characters/15/213467.jpg',
'The best anime is Taiyou Akari! http://cdn.myanimelist.net/images/characters/15/213473.jpg',
'The best anime is Tsukuyomi Luna! http://cdn.myanimelist.net/images/characters/12/213469.jpg',
'The best anime is Cerebrum! http://cdn.myanimelist.net/images/characters/6/222233.jpg',
'The best anime is Hoshino Tetsuro! http://cdn.myanimelist.net/images/characters/16/112752.jpg',
'The best anime is Kurono Kei! http://cdn.myanimelist.net/images/characters/2/33389.jpg',
'The best anime is Kishimoto Kei! http://cdn.myanimelist.net/images/characters/5/71428.jpg',
'The best anime is Katou Masaru! http://cdn.myanimelist.net/images/characters/7/71756.jpg',
'The best anime is Giovanni! http://cdn.myanimelist.net/images/characters/14/48358.jpg',
'The best anime is Campanella! http://cdn.myanimelist.net/images/characters/14/48359.jpg',
'The best anime is Hayashida Nana! http://cdn.myanimelist.net/images/characters/5/229417.jpg',
'The best anime is https://www.youtube.com/watch?v=axGxweYJ-SI',
'The best anime is Kaga Kouko! http://cdn.myanimelist.net/images/characters/13/221699.jpg',
'The best anime is Yanagisawa Mitsuo! http://cdn.myanimelist.net/images/characters/8/238235.jpg',
'The best anime is Oka Chinami "MISS ULTRASONIC"! http://cdn.myanimelist.net/images/characters/11/227759.jpg',
'The best anime is Ouma Shu! http://cdn.myanimelist.net/images/characters/14/139133.jpg',
'The best anime is Yuzuriha Inori! http://cdn.myanimelist.net/images/characters/10/139621.jpg',
'The best anime is Brandon Heat! http://cdn.myanimelist.net/images/characters/10/80723.jpg',
'The best anime is Harry Macdowel! http://cdn.myanimelist.net/images/characters/9/99385.jpg',
'The best anime is Rakka! http://cdn.myanimelist.net/images/characters/10/54949.jpg',
'The best anime is Reki! http://cdn.myanimelist.net/images/characters/9/109099.jpg',
'The best anime is Kuu! http://cdn.myanimelist.net/images/characters/8/77622.jpg',
'The best anime is Nemu! http://cdn.myanimelist.net/images/characters/15/87451.jpg',
'The best anime is Kana! http://cdn.myanimelist.net/images/characters/9/87448.jpg',
'The best anime is Anzu! http://cdn.myanimelist.net/images/characters/7/77378.jpg',
'The best anime is Hiiragi! http://cdn.myanimelist.net/images/characters/16/77371.jpg',
'The best anime is Koume! http://cdn.myanimelist.net/images/characters/15/77379.jpg',
'The best anime is Tsuchida Naozumi! http://cdn.myanimelist.net/images/characters/5/77375.jpg',
'The best anime is Yamamoto Nanako! http://cdn.myanimelist.net/images/characters/16/77374.jpg',
'The best anime is Hinagiku! http://cdn.myanimelist.net/images/characters/15/82233.jpg',
'The best anime is Kawashiro! http://cdn.myanimelist.net/images/characters/16/78100.jpg',
'The best anime is Kusano Rouze! http://cdn.myanimelist.net/images/characters/14/78097.jpg',
'The best anime is Mariel! http://cdn.myanimelist.net/images/characters/6/61860.jpg',
'The best anime is Joseph Carter Jones! http://cdn.myanimelist.net/images/characters/6/84452.jpg',
'The best anime is Simon Kaina! http://cdn.myanimelist.net/images/characters/15/84273.jpg',
'The best anime is Matthew Denton! http://cdn.myanimelist.net/images/characters/6/97501.jpg',
'The best anime is Lina Davis! http://cdn.myanimelist.net/images/characters/10/84272.jpg',
'The best anime is Gregory Makiko! http://cdn.myanimelist.net/images/characters/13/113998.jpg',
'The best anime is Ichikawa Hishiyasu! http://cdn.myanimelist.net/images/characters/9/114025.jpg',
'The best anime is Katou Anna! http://cdn.myanimelist.net/images/characters/3/204327.jpg',
'The best anime is Matsutaka Nanako! http://cdn.myanimelist.net/images/characters/9/149689.jpg',
'The best anime is Meshiya Kenji! http://cdn.myanimelist.net/images/characters/6/102304.jpg',
'The best anime is Mizukoshi Miwako! http://cdn.myanimelist.net/images/characters/14/99634.jpg',
'The best anime is Musashi Komugi! http://cdn.myanimelist.net/images/characters/4/114144.jpg',
'The best anime is Yesterday Taguchi! http://cdn.myanimelist.net/images/characters/9/204325.jpg',
'The best anime is Kino! http://cdn.myanimelist.net/images/characters/6/94294.jpg',
'The best anime is Hermes! http://cdn.myanimelist.net/images/characters/2/40465.jpg',
'The best anime is Aoyagi Kanna! http://cdn.myanimelist.net/images/characters/2/105043.jpg',
'The best anime is Flower! http://cdn.myanimelist.net/images/characters/9/147511.jpg',
'The best anime is Ishikawa Goemon XIII! http://cdn.myanimelist.net/images/characters/10/32603.jpg',
'The best anime is Daisuke Jigen! http://cdn.myanimelist.net/images/characters/6/100878.jpg',
'The best anime is Arsene Lupin III! http://cdn.myanimelist.net/images/characters/16/149939.jpg',
'The best anime is Mine Fujiko! http://cdn.myanimelist.net/images/characters/8/149887.jpg',
'The best anime is Zenigata Koichi! http://cdn.myanimelist.net/images/characters/6/100882.jpg',
'The best anime is Ando Mahoro! http://cdn.myanimelist.net/images/characters/5/57265.jpg',
'The best anime is Ando Minawa! http://cdn.myanimelist.net/images/characters/8/65418.jpg',
'The best anime is Fukuzawa Yumi! http://cdn.myanimelist.net/images/characters/6/55462.jpg',
'The best anime is Hasekura Rei! http://cdn.myanimelist.net/images/characters/11/67174.jpg',
'The best anime is Ogasawara Sachiko! http://cdn.myanimelist.net/images/characters/9/115897.jpg',
'The best anime is Katou Sei! http://cdn.myanimelist.net/images/characters/8/105543.jpg',
'The best anime is Shimazu Yoshino! http://cdn.myanimelist.net/images/characters/5/101922.jpg',
'The best anime is Toudou Shimako! http://cdn.myanimelist.net/images/characters/3/48073.jpg',
'The best anime is Miyamae Kanako! http://cdn.myanimelist.net/images/characters/2/110877.jpg',
'The best anime is Shindou Mariya! http://cdn.myanimelist.net/images/characters/6/44962.jpg',
'The best anime is Shinouji Matsurika! http://cdn.myanimelist.net/images/characters/2/42568.jpg',
'The best anime is God (Maria Holic)! http://cdn.myanimelist.net/images/characters/3/102416.jpg',
'The best anime is Geist! http://cdn.myanimelist.net/images/characters/13/207997.jpg',
'The best anime is Kasugano Midori! http://cdn.myanimelist.net/images/characters/9/35916.jpg',
'The best anime is Sawamura Seiji! http://cdn.myanimelist.net/images/characters/8/68710.jpg',
'The best anime is Ayase Takako! http://cdn.myanimelist.net/images/characters/5/81620.jpg',
'The best anime is Kurousagi! http://cdn.myanimelist.net/images/characters/15/197167.jpg',
'The best anime is Kasukabe You! http://cdn.myanimelist.net/images/characters/9/192541.jpg',
'The best anime is Kusou Asuka! http://cdn.myanimelist.net/images/characters/14/210945.jpg',
'The best anime is Sakamaki Izayoi! http://cdn.myanimelist.net/images/characters/11/198719.jpg',
'The best anime is Shiroyasha! http://cdn.myanimelist.net/images/characters/4/199451.jpg',
'The best anime is Munto! http://cdn.myanimelist.net/images/characters/5/53921.jpg',
'The best anime is Hidaka Yumemi! http://cdn.myanimelist.net/images/characters/14/47228.jpg',
'The best anime is Ichigo! http://cdn.myanimelist.net/images/characters/11/89778.jpg',
'The best anime is Genma Iroe! http://cdn.myanimelist.net/images/characters/11/214523.jpg',
'The best anime is Okamoto Hazuki! http://cdn.myanimelist.net/images/characters/13/250421.jpg',
'The best anime is Sakamaki Makina! http://cdn.myanimelist.net/images/characters/5/250425.jpg',
'The best anime is Potemayo! http://cdn.myanimelist.net/images/characters/7/11637.jpg',
'The best anime is Guchuko! http://cdn.myanimelist.net/images/characters/15/31033.jpg',
'The best anime is Kasugano Nene! http://cdn.myanimelist.net/images/characters/10/55299.jpg',
'The best anime is Plain Sill! http://cdn.myanimelist.net/images/characters/14/218703.jpg',
'The best anime is Rance! http://cdn.myanimelist.net/images/characters/12/70087.jpg',
'The best anime is Shimizu Sayaka! http://cdn.myanimelist.net/images/characters/15/212553.jpg',
'The best anime is Takagi Mai! http://cdn.myanimelist.net/images/characters/6/212575.jpg',
'The best anime is Takamura Yuka! http://cdn.myanimelist.net/images/characters/6/212557.jpg',
'The best anime is Shinku! http://cdn.myanimelist.net/images/characters/16/89707.jpg',
'The best anime is Suigintou! http://cdn.myanimelist.net/images/characters/7/80234.jpg',
'The best anime is Desu! http://cdn.myanimelist.net/images/characters/7/50895.jpg',
'The best anime is Boku! http://cdn.myanimelist.net/images/characters/3/89842.jpg',
'The best anime is Patema! http://cdn.myanimelist.net/images/characters/12/150753.jpg',
'The best anime is Ichise! http://cdn.myanimelist.net/images/characters/12/79950.jpg',
'The best anime is Oonishi Keigo! http://cdn.myanimelist.net/images/characters/2/214599.jpg',
'The best anime is Kazuho Yoshii! http://cdn.myanimelist.net/images/characters/16/210019.jpg',
'The best anime is Kaburagi Kotetsu! http://cdn.myanimelist.net/images/characters/2/143277.jpg',
'The best anime is Barnaby Brooks Jr.! http://cdn.myanimelist.net/images/characters/2/133051.jpg',
'The best anime is Haru JF1! http://cdn.myanimelist.net/images/characters/7/171753.jpg',
'The best anime is Sanada Yuki! http://cdn.myanimelist.net/images/characters/9/162921.jpg',
'The best anime is Usami Natsuki! http://cdn.myanimelist.net/images/characters/13/165029.jpg',
'The best anime is Yamada Akira Agarkar! http://cdn.myanimelist.net/images/characters/4/164369.jpg',
'The best anime is Hakuoro! http://cdn.myanimelist.net/images/characters/2/80240.jpg',
'The best anime is Utawarerumono! http://cdn.myanimelist.net/images/characters/2/80240.jpg',
'The best anime is Yuzuha! http://cdn.myanimelist.net/images/characters/3/92004.jpg',
'The best anime is Eruruu! http://cdn.myanimelist.net/images/characters/4/15058.jpg',
'The best anime is Aruruu! http://cdn.myanimelist.net/images/characters/8/33742.jpg',
'The best anime is Touka! http://cdn.myanimelist.net/images/characters/16/50168.jpg',
'The best anime is Kamyu! http://cdn.myanimelist.net/images/characters/8/33749.jpg',
'The best anime is Amururineuruka Kuya! http://cdn.myanimelist.net/images/characters/13/33753.jpg',
'The best anime is Isone Kotoha! http://cdn.myanimelist.net/images/characters/4/253147.jpg',
'The best anime is Nanami Ao! http://cdn.myanimelist.net/images/characters/11/253145.jpg',
'The best anime is Yarizakura Hime! http://cdn.myanimelist.net/images/characters/15/68736.jpg',
'The best anime is Azuma Rin! http://cdn.myanimelist.net/images/characters/6/102559.jpg',
'The best anime is Victor Juli Frankenstein! http://cdn.myanimelist.net/images/characters/5/253139.jpg',
'The best anime is Kasugano Sora! http://cdn.myanimelist.net/images/characters/10/101109.jpg',
'The best anime is Kurama! http://cdn.myanimelist.net/images/characters/13/94796.jpg',
'The best anime is Hiei! http://cdn.myanimelist.net/images/characters/6/94437.jpg',
'The best anime is Kuwabara Kazuma! http://cdn.myanimelist.net/images/characters/11/34968.jpg',
'The best anime is Urameshi Yusuke! http://cdn.myanimelist.net/images/characters/9/101575.jpg',
'The best anime is Botan! http://cdn.myanimelist.net/images/characters/4/44563.jpg',
'The best anime is Yukina! http://cdn.myanimelist.net/images/characters/3/78418.jpg',
'The best anime is Tanaka Yutori! http://cdn.myanimelist.net/images/characters/11/87465.jpg',
'The best anime is Tsumekomi Shiori! http://cdn.myanimelist.net/images/characters/12/87495.jpg',
'The best anime is Dankain Reiko! http://cdn.myanimelist.net/images/characters/9/167127.jpg',
'The best anime is Elucia de Lute Ima! http://cdn.myanimelist.net/images/characters/4/94386.jpg',
'The best anime is Haqua du Lot Herminium! http://cdn.myanimelist.net/images/characters/10/112281.jpg',
'The best anime is Ayukawa Tenri! http://cdn.myanimelist.net/images/characters/6/93160.jpg',
'The best anime is uemoto Sumire! http://cdn.myanimelist.net/images/characters/15/93159.jpg',
'The best anime is Onodera Yuichi! http://cdn.myanimelist.net/images/characters/10/219321.jpg',
'The best anime is Hebitsuka Gesumi! http://cdn.myanimelist.net/images/characters/15/236299.jpg',
'The best anime is Himemiya Anthy! http://cdn.myanimelist.net/images/characters/11/78521.jpg',
'The best anime is Tenjou Utena! http://cdn.myanimelist.net/images/characters/9/84871.jpg',
'The best anime is Abriel Nei Debrusc Borl Paryun Lafiel! http://cdn.myanimelist.net/images/characters/2/46766.jpg',
'The best anime is Linn Ssynec Rocr Dreuc Haïder Ghintec! http://cdn.myanimelist.net/images/characters/10/119868.jpg',
'The best anime is Spoor Aron Sekpadao Letopanyu Beneej! http://cdn.myanimelist.net/images/characters/2/109085.jpg',
'The best anime is Saber! http://cdn.myanimelist.net/images/characters/2/241405.jpg',
'The best anime is Archer! http://cdn.myanimelist.net/images/characters/5/119974.jpg',
'The best anime is Emiya Shirou! http://cdn.myanimelist.net/images/characters/5/256621.jpg',
'The best anime is Tohsaka Rin! http://cdn.myanimelist.net/images/characters/14/31621.jpg',
'The best anime is Rider! http://cdn.myanimelist.net/images/characters/7/89715.jpg',
'The best anime is Gilgamesh! http://cdn.myanimelist.net/images/characters/5/135627.jpg',
'The best anime is Fujimura Taiga! http://cdn.myanimelist.net/images/characters/6/31616.jpg',
'The best anime is Matou Sakura! http://cdn.myanimelist.net/images/characters/4/165044.jpg',
'The best anime is Illyasviel von Einzbern! http://cdn.myanimelist.net/images/characters/8/31609.jpg',
'The best anime is Ciel! http://cdn.myanimelist.net/images/characters/10/189508.jpg',
'The best anime is Arcueid Brunstud! http://cdn.myanimelist.net/images/characters/4/126881.jpg',
'The best anime is Tohno Shiki! http://cdn.myanimelist.net/images/characters/10/72812.jpg',
'The best anime is Tohno Akiha! http://cdn.myanimelist.net/images/characters/16/91627.jpg',
'The best anime is Hisui! http://cdn.myanimelist.net/images/characters/11/153955.jpg',
'The best anime is Kohaku! http://cdn.myanimelist.net/images/characters/6/130145.jpg',
'The best anime is Aozaki Aoko! http://cdn.myanimelist.net/images/characters/8/78770.jpg',
'The best anime is Yumizuka Satsuki! http://cdn.myanimelist.net/images/characters/14/78578.jpg',
'The best anime is Ryougi Shiki! http://cdn.myanimelist.net/images/characters/8/79870.jpg',
'The best anime is Edogawa Conan! http://cdn.myanimelist.net/images/characters/10/146275.jpg',
'The best anime is Kudo Shinichi! http://cdn.myanimelist.net/images/characters/7/147843.jpg',
'The best anime is Mouri Ran! http://cdn.myanimelist.net/images/characters/15/109320.jpg',
'The best anime is Momozono Nanami! http://cdn.myanimelist.net/images/characters/16/185573.jpg',
'The best anime is Komugi http://cdn.myanimelist.net/images/characters/14/243865.jpg',
'The best anime is Akimoto Komachi! http://cdn.myanimelist.net/images/characters/12/231349.jpg',
'The best anime is Kasugano Urara! http://cdn.myanimelist.net/images/characters/5/136459.jpg',
'The best anime is Minazuki Karen! http://cdn.myanimelist.net/images/characters/11/136655.jpg',
'The best anime is Natsuki Rin! http://cdn.myanimelist.net/images/characters/5/231331.jpg',
'The best anime is Yumehara Nozomi! http://cdn.myanimelist.net/images/characters/11/231373.jpg',
'The best anime is Aono Miki! http://cdn.myanimelist.net/images/characters/10/255479.jpg',
'The best anime is Higashi Setsuna! http://cdn.myanimelist.net/images/characters/12/122691.jpg',
'The best anime is Momozono Love! http://cdn.myanimelist.net/images/characters/4/136137.jpg',
'The best anime is Yamabuki Inori! http://cdn.myanimelist.net/images/characters/5/253637.jpg',
'The best anime is Mimino Kurumi! http://cdn.myanimelist.net/images/characters/3/252001.jpg',
'The best anime is Kujou Hikari! http://cdn.myanimelist.net/images/characters/9/253615.jpg',
'The best anime is Misumi Nagisa! http://cdn.myanimelist.net/images/characters/3/222481.jpg',
'The best anime is Yukishiro Honoka! http://cdn.myanimelist.net/images/characters/9/222491.jpg',
'The best anime is Hyuuga Saki! http://cdn.myanimelist.net/images/characters/16/97579.jpg',
'The best anime is Mishou Mai! http://cdn.myanimelist.net/images/characters/8/97572.jpg',
'The best anime is Harumi Kiyama! http://cdn.myanimelist.net/images/characters/6/77133.jpg',
'The best anime is Utsugi Mikoto! http://cdn.myanimelist.net/images/characters/2/95983.jpg',
'The best anime is Hatsuno Hana! http://cdn.myanimelist.net/images/characters/16/95977.jpg',
'The best anime is Daijuuji Kurou! http://cdn.myanimelist.net/images/characters/14/154239.jpg',
'The best anime is Al-Azif Necronomicon! http://cdn.myanimelist.net/images/characters/10/67061.jpg',
'The best anime is Elsa! http://cdn.myanimelist.net/images/characters/12/109029.jpg',
'The best anime is Sid Vicious! http://myanimelist.net/images/characters/4/284773.jpg',
'The best anime is Shidare Hotaru! http://myanimelist.net/images/characters/6/293752.jpg',
'The best anime is Saya Endou! http://myanimelist.net/images/characters/16/300345.jpg',
'The best anime is Marimo Bandou! http://myanimelist.net/images/characters/16/186037.jpg',
'The best anime is Kanae Shinjou! http://myanimelist.net/images/characters/8/190196.jpg',
'The best anime is Takamiya Masumo! http://myanimelist.net/images/characters/15/190012.jpg',
'The best anime is Yuri Oshimoto! http://myanimelist.net/images/characters/14/184983.jpg',
'The best anime is Chikane Himemiya!  http://cdn.myanimelist.net/images/characters/13/112468.jpg',
'The best anime is Himeko Kurusugawa! http://cdn.myanimelist.net/images/characters/7/89226.jpg',
'The best anime is Otoha Kisaragi! http://cdn.myanimelist.net/images/characters/12/114519.jpg',
'The best anime is Setsuna! http://cdn.myanimelist.net/images/characters/6/43746.jpg',
'The Best anime is Kuu Shiratori! http://cdn.myanimelist.net/images/characters/16/115273.jpg',
'The best anime is Himiko! http://cdn.myanimelist.net/images/characters/13/43699.jpg',
'The best anime is Kaon! http://cdn.myanimelist.net/images/characters/7/43698.jpg',

    ];
  }

  message(from, to, text) {
    if (text.startsWith(`!anim`)) {
      log(`${from} on: ${text}`);

      const result = this.responses[Math.floor(Math.random() * this.responses.length)];
      this.send(to, `${from}: ${result}`);
    }
  }

  help(from) {
    this.client.notice(from, `.8ball question; randomly outputs response`);
  }
}
