import debug from 'debug';
import { Command } from './command.js';

const log = debug('Quotes');

export class Quotes extends Command {
  constructor(client) {
    super(client);
    this.responses = new Map();
    this.responses.set('!quotes', "There are 379 quotes!")
    this.responses.set('!quote 1', 'Quote 1: I have hiccups at the moment... so be back in an hour. - Salamence20');
    this.responses.set('!quote 2', 'Quote 2: EA is hiding this, they are pretending like they don`t know what I am talking about. This is completly redundant... - Salamence20');
    this.responses.set('!quote 3', 'Quote 3: sorry for acting all noobish, but whats so hard about a song about cherries? - Salamence20, on Cherry Bomb');
    this.responses.set('!quote 4', 'Quote 4: How about Coheed and Cambria OMB - Salamence20');
    this.responses.set('!quote 5', 'Quote 5: HMX ruins songs. - Salamence20');
    this.responses.set('!quote 6', 'Quote 6: HAHAHA Talkies r easy I got a 100 on Testify. Just say the wurds - VOCKSNUB, on Alive (Live)`s broken talky');
    this.responses.set('!quote 7', 'Quote 7: Is there any plans for Dream Theater DLC If they Say Yes: I will eat a tea bag If they say no: I hate them - Salamence20 on someone meeting HMX');
    this.responses.set('!quote 8', 'Quote 8: WIIIIILSOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOON! - solrac');
    this.responses.set('!quote 9', 'Quote 9: Inv4der is a sexy beast - Erkle');
    this.responses.set('!quote 10', 'Quote 10: [21:51] <+Wyatt> SHUT UP NO ONE LIKES YOU');
    this.responses.set('!quote 11', 'Quote 11: <+arte> bye semenlance');
    this.responses.set('!quote 12', 'Quote 12: [21:55] <+Angels2002> HAVE YOU CAUGHT PICKACHU YET????????');
    this.responses.set('!quote 13', 'Quote 13: <+Salamence20> !Ruels');
    this.responses.set('!quote 14', 'Quote 14: <+POKE|windupFAIL> inv4der Salamence20 is sexually aroused by 300x40 images');
    this.responses.set('!quote 15', 'Quote 15: <+SteroidPirate> Canola oil is actually rapeseed oil...');
    this.responses.set('!quote 16', 'Quote 16: <+POKE-JJ> I`m gonna take trogdor into PS and experiment with him');
    this.responses.set('!quote 17', 'Quote 17: This just might be the best OMB album out there` - 82erkle on Texas Flood');
    this.responses.set('!quote 18', 'Quote 18: I would FC all of these songs but i`m listening to music on my laptop.` - Lefty on Iron Maiden Bass');
    this.responses.set('!quote 19', 'Quote 19: Could I use my DLC from my wii to my 360?` - Some retard');
    this.responses.set('!quote 20', 'Quote 20: MY GENERATION MEDIUM BASS FC MOTHA FUCKAS` - erkle82');
    this.responses.set('!quote 21', 'Quote 21: <+Navy|Unplugged> don`t think you were here when my sister screwed me');
    this.responses.set('!quote 22', 'Quote 22: F.C.P.R.E.M.I.X. (Would remind me of something like Last Resort)` - Salamence20');
    this.responses.set('!quote 23', 'Quote 23: no, I`d say that erkle82 is multiple dicks` - inv4der');
    this.responses.set('!quote 24', 'Quote 24: <+sonicdude164|fbwoo> ill go do cows');
    this.responses.set('!quote 25', 'Quote 25: Ur moms a fuckin noob! Blink r 1 of the best bands ever u son of a dick! Go eat crap!` - some retard on youtube');
    this.responses.set('!quote 26', 'Quote 26: <Fretz> I like a nice teabag every so often');
    this.responses.set('!quote 27', 'Quote 27: [02:49am] 4[Carungimon4] I GOLTS A COBBLE BADGE MOTHER FUCKAS');
    this.responses.set('!quote 28', 'Quote 28: Jesus has finally got on the wii` - Salamence20');
    this.responses.set('!quote 29', 'Quote 29: <@ChanServ> ManfredvonKarma: Meow, I`m a cat!');
    this.responses.set('!quote 30', 'Quote 30: War ensable.... Whats so hard about that song` - Salamence20');
    this.responses.set('!quote 31', 'Quote 31: Don`t devoice me, bro!` - Arte');
    this.responses.set('!quote 32', 'Quote 32: More Ideas: YMB VoxBassTar (Kinda Like the SWW Banner');
    this.responses.set('!quote 33', 'Quote 33: Ok, he`s gone. Add more quotes.` - DanSoup');
    this.responses.set('!quote 34', 'Quote 34: <HungrySanta> I don`t quote myself, which also, in turn, means I don`t want to be quoted');
    this.responses.set('!quote 35', 'Quote 35: Hungry HungrySanta|Hungry is Hungry, apparently` - inv4der');
    this.responses.set('!quote 36', 'Quote 36: I was playing around with it in #BAWhero one day` - inv4der');
    this.responses.set('!quote 37', 'Quote 37: naa, lets get octarium` - semenlance on Dream Theater DLC');
    this.responses.set('!quote 38', 'Quote 38: Sala20|FuckPepsi: 1 Salabyte = Infinty, never runs out');
    this.responses.set('!quote 39', 'Quote 39: I reported, expect a band soon` - Salamence20');
    this.responses.set('!quote 40', 'Quote 40: IdiotServ is back! Yay!` - inv4der');
    this.responses.set('!quote 41', 'Quote 41: where is idiotserv baww');
    this.responses.set('!quote 42', 'Quote 42: who cares about the other songs, they`re been FCd` -arte');
    this.responses.set('!quote 43', 'Quote 43: So... HungrySanta is Hungry? who would`ve guessed?` - inv4der');
    this.responses.set('!quote 44', 'Quote 44: I am really about that...` - pizzzapizza');
    this.responses.set('!quote 45', 'Quote 45: <arte> i imagine paul mccartney screaming at some kid about how it`s theirs and his birthday');
    this.responses.set('!quote 46', 'Quote 46: <fuse> omfg Yur0wn is my favorite person in the world. I`d love to meet up with him and have buttsecks sometime.');
    this.responses.set('!quote 47', 'Quote 47: To play this disc, put it in an Xbox 360 console` - arte`s 360, on having RB2 inserted');
    this.responses.set('!quote 48', 'Quote 48: <NvayCherub> !7ball So now we can have make-up sex?');
    this.responses.set('!quote 49', 'Quote 49: <+Carungi> flammable, your like 14 your dick doesnt even work yet');
    this.responses.set('!quote 50', 'Quote 50: <Drunkolai> also not gonna get any pussy tonight bevcause my pussy isn`t answering her phone');
    this.responses.set('!quote 51', 'Quote 51: * Flammablelion is now known as Fagboylion');
    this.responses.set('!quote 52', 'Quote 52: <vix> its sad when the rapist gets away because no one believes the girl | <vix> this is not that far from that situation` - Vix on e-drama');
    this.responses.set('!quote 53', 'Quote 53: <POKE-JJ> leave me alone, I`m watching porn');
    this.responses.set('!quote 54', 'Quote 54: <TeamPOKE-JJ> dog of bag poo');
    this.responses.set('!quote 55', 'Quote 55: <dcuk> i have an arte fetish obv.');
    this.responses.set('!quote 56', 'Quote 56: (in response to being asked why he was sad) <Silly|sad> yewb`s shitty pc just screwed me over and i died on runescape');
    this.responses.set('!quote 57', 'Quote 57: <JoeTheAncientOne> CRASHING THROUGH THE BOUNDARIES LUNACY HAS FOUND ME. MY CAMERA`S OUT OF BATTERY.');
    this.responses.set('!quote 58', 'Quote 58: <HungrySanta> Invisalign officially does NOT count for the earning of the Killer Queen Day of Braces FC banner.');
    this.responses.set('!quote 59', 'Quote 59: Yes, it does.` - FishEater, on quote 58');
    this.responses.set('!quote 60', 'Quote 60: <+fusebot> NvayCherub must NvayCherub NvayCherub!');
    this.responses.set('!quote 61', 'Quote 61: <louster200> AKA: I`m a desperate 12 year old');
    this.responses.set('!quote 62', 'Quote 62: <@inv4der> you can play with me arte');
    this.responses.set('!quote 63', 'Quote 63: (in response to being asked why he was happy) <Silly|happy> because yewb`s shitty pc didn`t screw me over and I didn`t die on runescape');
    this.responses.set('!quote 64', 'Quote 64: Actually, if you think about it, It is Matt and Evan`s fault.` - Vickseeneetuhh on stuff.');
    this.responses.set('!quote 65', 'Quote 65: [17:26] <robbyx4595> ok, if i FC Rock Band Beatles on drums I will fly out to Wisconsin and lick erkle`s weiner.');
    this.responses.set('!quote 66', 'Quote 66: StephenAtHomeobama wants to kill old people. so does arthritis. so by the transitive property, oh god, obama is arthritis');
    this.responses.set('!quote 67', 'Quote 67: i know all about fantasy stuff, just not football` - arte');
    this.responses.set('!quote 68', 'Quote 68: <Silly> FUCK YOU INAVD3R U R A FOLL');
    this.responses.set('!quote 69', 'Quote 69: <+`Silly> hey guys 69 is a funny number becuas eit is also a sexual position lol!');
    this.responses.set('!quote 70', 'Quote 70: <TheLonging> .!addquote HungrySanta is a whore');
    this.responses.set('!quote 71', 'Quote 71: <@Silly> HOLY JESUS TITTYFUCKING WHAT THE GODDAMN HOLY SHIT');
    this.responses.set('!quote 72', 'Quote 72: <@SillyScape> we`re just all japanese schoolgirls');
    this.responses.set('!quote 73', 'Quote 73: <Nikolai> bannerhero, i pose a question to you:');
    this.responses.set('!quote 74', 'Quote 74: <Carungi> no i will not touch your sack');
    this.responses.set('!quote 75', 'Quote 75: <+Carungi> so i named all the handymen in my game angels2002');
    this.responses.set('!quote 76', 'Quote 76: <THABEAST721> oh no my water slide got stuck');
    this.responses.set('!quote 77', 'Quote 77: <+Carungi> this guy thought `this park is really celan and tidy` and then threw up');
    this.responses.set('!quote 78', 'Quote 78: <louster200|GHSH|XGtr> I WANNA COCK!');
    this.responses.set('!quote 79', 'Quote 79: <cdylan13> At I`ve cream trucks');
    this.responses.set('!quote 80', 'Quote 80: <erkle82|PushItOMBFC> HOW WOULD YOU KNOW I LIKE COCK?!');
    this.responses.set('!quote 81', 'Quote 81: <robbyx4595> erkle, how big is your penis');
    this.responses.set('!quote 82', 'Quote 82: <POKE-JJ>: erkle82|PushItOMBFC, more like erkle82|analOMBFC');
    this.responses.set('!quote 83', 'Quote 83: <ManfredvonKarma> Figures that erkle would rather have a location on SH about licking ass than a real location');
    this.responses.set('!quote 84', 'Quote 84: <Flammablelion> POKE-JJ: What kind of anal butt cream do you use');
    this.responses.set('!quote 85', 'Quote 85: <erkle82> im a homo who loves anal cream');
    this.responses.set('!quote 86', 'Quote 86: Dick fuck cockels` - SteroidPirate');
    this.responses.set('!quote 87', 'Quote 87: <@ManfredvonKarma> Yeah, you know I love me some all male incest');
    this.responses.set('!quote 88', 'Quote 88: <NvayCherub> My mom is hotter than your mom');
    this.responses.set('!quote 89', 'Quote 89: <SpoonMan> i cant stop jizzing');
    this.responses.set('!quote 90', 'Quote 90: <@inv4der> I could indeed song it though');
    this.responses.set('!quote 91', 'Quote 91: <@ChanServ> FishEater: Are you mad?! <@FishEater> Sounds like a no.` - ChanServ on if Salvatore will ever FC Rude Mood.');
    this.responses.set('!quote 92', 'Quote 92: <Salvatore|Sunburn> !8ball Give me a girlfriend. <@ChanServ> Salvatore|Sunburn: Absolutely not.');
    this.responses.set('!quote 93', 'Quote 93: <FuckingOwnt> Psh, arte doesn`t have any friends.');
    this.responses.set('!quote 94', 'Quote 94: <RingoStarr> I`VE GOT BLISTERS ON MAH FINGAS');
    this.responses.set('!quote 95', 'Quote 95: <@HMX^IdiotServ> RIP was tracked by special guest Chris Vance');
    this.responses.set('!quote 96', 'Quote 96: <NvayCherub> it`s hilarious to FUCK YOUR MOM');
    this.responses.set('!quote 97', 'Quote 97: <robbyx4595> i wish to be the little girl');
    this.responses.set('!quote 98', 'Quote 98: I AM A HELPFUL HAMSTER` - inv4der');
    this.responses.set('!quote 99', 'Quote 99: * @ManfredvonKarma goes off to work his job a Microsoft');
    this.responses.set('!quote 100', 'Quote 100: Because I LOVE YOU [ManfredvonKarma]` - NvayCherub coming out of the closet');
    this.responses.set('!quote 101', 'Quote 101: <@FishServ> !7 Will ManfredvonKarma be alone forever? <@IdiotServ> FishServ: Seems likely.');
    this.responses.set('!quote 102', 'Quote 102: [03:00:30pm] 4[Salvatore|Sunburn4] !7ball Am I a cool guy?');
    this.responses.set('!quote 103', 'Quote 103: (>`_`)># at first i had a waffle #<(`_`<) i was gonna give it to you (>`#`<) but then i got hungry (>`-`<) so i ated it');
    this.responses.set('!quote 104', 'Quote 104: `I can pee, therefore, my dick works.` - Salvatore|BURP');
    this.responses.set('!quote 105', 'Quote 105: <Yur0wn> HEY GUYS I HAVE A VAGINA');
    this.responses.set('!quote 106', 'Quote 106: <@PhishEater> !7 Sex with ChanServ? <@IdiotServ> PhishEater: Ask me later, I`m having sex with ChanServ at the moment.');
    this.responses.set('!quote 107', 'Quote 107: [05:50] <@ahelpfulhamster> Fish, it said `hylianhero or w.e fails she `banned` me 4 mispelling words but she 4got about the register btn nd nao ill keep making thes O ND SUM CAPS 2 PISS OF THT WHORE kthxbai`');
    this.responses.set('!quote 108', 'Quote 108: that`s not my job MvK` - ahelpfulhamster, being unhelpful');
    this.responses.set('!quote 109', 'Quote 109: <S1ckH4nds> So hopefully I don`t sound like a bag of dicks for the rest of my life.');
    this.responses.set('!quote 110', 'Quote 110: [07:21:51pm] 4[S1ckH4nds|Laptop4] Those chords are charted properly, and I`m a bag of dicks.');
    this.responses.set('!quote 111', 'Quote 111: I think butt3rz just likes my style is all. - 82erkle');
    this.responses.set('!quote 112', 'Quote 112: <@Prong1978> Well fuse can kiss my ass!');
    this.responses.set('!quote 113', 'Quote 113: So I was gonna grind for the IRS guitar FC, but I decided that would be too taxing` - inv4der');
    this.responses.set('!quote 114', 'Quote 114: <@inv4der> quote 114 needs deleted | <@inv4der> because it sucks');
    this.responses.set('!quote 115', 'Quote 115: <cdylan13> does not computer');
    this.responses.set('!quote 116', 'Quote 116: <+Nikolai> now i`m sucking fuse');
    this.responses.set('!quote 117', 'Quote 117: <Angels2002> MvK reads furry comics.');
    this.responses.set('!quote 118', 'Quote 118: <+Tenfrente> My best friend, and love interest, is a girl | <Yewb> your love interest is a girl?!');
    this.responses.set('!quote 119', 'Quote 119: <simpsonfreak17|scorpion> FishEater do me now');
    this.responses.set('!quote 120', 'Quote 120: <+arteGH5> fuse likes to drop the soap');
    this.responses.set('!quote 121', 'Quote 121: I love Chris Vance` - duck|out');
    this.responses.set('!quote 122', 'Quote 122: <Flammablelion-1> I`m gonna go cry brb');
    this.responses.set('!quote 123', 'Quote 123: May I take part? I should get it first day, but if not, I`ll let you guys know. - erkle on the Beatles FGOMBFC');
    this.responses.set('!quote 124', 'Quote 124: <SteroidPirate> cockfucksuckducktruck');
    this.responses.set('!quote 125', 'Quote 125: <stewo|GR2R|FC> i had sex with fuse');
    this.responses.set('!quote 126', 'Quote 126: <@ManfredvonKarma> Just because I considered whether or not it was easier to climb a wall of erect dicks than a wall of flccid ones doesn`t mean anything');
    this.responses.set('!quote 127', 'Quote 127: ...I was running around putting my face where the balls would hit it...` - ManfredvonKarma');
    this.responses.set('!quote 128', 'Quote 128: <@Silly|MockTheWeek> I got PMed about my last couple of avatard girls');
    this.responses.set('!quote 129', 'Quote 129: <@ManfredvonKarma> These nuts are good in my mouth');
    this.responses.set('!quote 130', 'Quote 130: <drifter1717> i need to drown it in vagina');
    this.responses.set('!quote 131', 'Quote 131: <+arte> everything about fuse sucks | <fuse> pretty sure a lot of people agree');
    this.responses.set('!quote 132', 'Quote 132: * @ChanServ (ChanServ@Services.GameSurge.net) Quit (oenoes!)');
    this.responses.set('!quote 133', 'Quote 133: [On Prof. Layton and the Curious Village] <JODIsBack> what could have scared the cat? who committed murder? am i playing pheonix wright or something?');
    this.responses.set('!quote 134', 'Quote 134: <robbyx4595> I HERD U LIEK METAL AND BEATLES SO I PPUT MIXELPIX IN YOUR RBB SO YOU CAN ROCK OUT WHEN YOU TROLL');
    this.responses.set('!quote 135', 'Quote 135: <@ManfredvonKarma> Cookie_Monster: I had a stuffed you when I was a child | <Cookie_Monster> did u molest me?');
    this.responses.set('!quote 136', 'Quote 136: <@Carungi> wyatt, shut up your fat ill ban you');
    this.responses.set('!quote 137', 'Quote 137: <@caRUNGIFSA> I HAVE A SMALL PENIS [repeated 15 times before exiting]');
    this.responses.set('!quote 138', 'Quote 138: <@Prong1978> Sightread FC of I`m The One on Expert Guitar!');
    this.responses.set('!quote 139', 'Quote 139: <+arte> did it with my tongue');
    this.responses.set('!quote 140', 'Quote 140: On Balloon Boy: <+POKE-JJ> stewo: HE`S BETTER THAN NJO AT TROLLING');
    this.responses.set('!quote 141', 'Quote 141: <@FishEater> I DO NOT CARE ABOUT MOUNTAIN MUD STAINS.');
    this.responses.set('!quote 142', 'Quote 142: What`s the need to inform all of us that this person is a guy not a dude?` - POKE-JJ');
    this.responses.set('!quote 143', 'Quote 143: <+bdown> If you don`t like `Penis` then fuck you');
    this.responses.set('!quote 144', 'Quote 144: <+sonicdude164> my 6 year old brother just told my mom `get the hell down here and make me a damn snack`');
    this.responses.set('!quote 145', 'Quote 145: <@Sillyyy> I gave a homeless person ��1 for a cup of tea. I wish the cunt would hurry up, I`m thirsty.');
    this.responses.set('!quote 146', 'Quote 146: <@ManfredvonKarma> I Can`t Keep My Eyes Off You is about stalking a girl named Patty | <@ManfredvonKarma> Best Day Ever is about the day when he finally rapes her');
    this.responses.set('!quote 147', 'Quote 147: <+bjw> YIFF IN HELL, MEXICO');
    this.responses.set('!quote 148', 'Quote 148: <+Angels2002> !7ball Are you a furry? | <@FishEater> Angels2002: SHUT UP YOU FUCKER!');
    this.responses.set('!quote 149', 'Quote 149: <@ManfredvonKarma> Fun fact: drifter1717 has a major erection thinking about yiffing with me, peok, and FishEater');
    this.responses.set('!quote 150', 'Quote 150: <+Angels2002> it`s like an episode of Maury, except with furries instead of fathers');
    this.responses.set('!quote 151', 'Quote 151: 2* @FishOutOfWater (~LethalFis@pool-71-107-66-226.lsanca.dsl-w.verizon.net) Quit (Quit: *gasp* Can`t... breathe... out... of... water... *gasp*)');
    this.responses.set('!quote 152', 'Quote 152: <@FishEater> Rule #1: Don`t be a dick. Rule #2: Follow Rule #1. <+NvayCherub> Rule #3: No furries <@FishEater> ^');
    this.responses.set('!quote 153', 'Quote 153: <+Flammable|15LRBFCs> YOU WANT TO SEE MY DICK');
    this.responses.set('!quote 154', 'Quote 154: <+robby|LOGDAY> that means prong would have to be like 11 when he gave birth to MvK');
    this.responses.set('!quote 155', 'Quote 155: <+Flammablelion> And to get her back I stuck pizza crust up my butt');
    this.responses.set('!quote 156', 'Quote 156: <@inv4der> so IdiotServ is cured of swine cancer?');
    this.responses.set('!quote 157', 'Quote 157: <+Flammablelion> well i am a dumb ass but I am book smart');
    this.responses.set('!quote 158', 'Quote 158: <arte> i am slightly concerned that i may become a pedophile later in life');
    this.responses.set('!quote 159', 'Quote 159: <+lolus> HAHAHA I`ve been here for months and have still managed to avoid being quoted. I FUCKING WIN!');
    this.responses.set('!quote 160', 'Quote 160: <@Nikolai> Her avatar, plus the name Paintmegorgeouss <@Nikolai> would indicate female <@Nikolai> but not necessary I guess <@arte> hey remember topazgrl <@Nikolai> just ask erkle <@arte> OHHH <@inv4der> AH IRONY');
    this.responses.set('!quote 161', 'Quote 161: <+erkle82> i thinks he`s soooooooooooooooooooooo hawt');
    this.responses.set('!quote 162', 'Quote 162: <@FishEater> OH CAR A DINGO GET IN THE :U');
    this.responses.set('!quote 163', 'Quote 163: <@Prong1978|KaraokeRev_820of1000> You know what? fuse is right.');
    this.responses.set('!quote 164', 'Quote 164: [00:49] <@arte> dude i could have used the stem cells to grow my other testicle back');
    this.responses.set('!quote 165', 'Quote 165: * POKE-JJ is now known as peeeeeeeeeeeeeeeeeeeeeeeeeeeee');
    this.responses.set('!quote 166', 'Quote 166: <+CHawk> Give me a sec duck and I`ll play with you');
    this.responses.set('!quote 167', 'Quote 167: <@Silly|GH5> the sense of accomplishment you get from beating it is sooooo fucking good');
    this.responses.set('!quote 168', 'Quote 168: ,  Massachusetts, AH AH AH of Furefure of Massachusetts, Massachusetts, this state Gaingain, Oh, and RO RO state, the state of Lara.');
    this.responses.set('!quote 169', 'Quote 169: doobers - `I have one question for you,how do you get the rectangle club accomplishment things that you have.`');
    this.responses.set('!quote 170', 'Quote 170: <+Flammablelion> Angels2002 we must bust');
    this.responses.set('!quote 171', 'Quote 171: <+Flammablelion> STOP ADDING MY MOM ON FB');
    this.responses.set('!quote 172', 'Quote 172: <+Angels2002> funny fuse fucks furries furiously');
    this.responses.set('!quote 173', 'Quote 173: <Otend1> Same here, except replace months with a couple weeks.');
    this.responses.set('!quote 174', 'Quote 174: (10:51:57 pm) <+Angels2002> i played rb drums in front of my mom and she told me to get a life');
    this.responses.set('!quote 175', 'Quote 175: <Flammablelion> my brother took my computer and read all of mIRC and he saw that i said you were cute');
    this.responses.set('!quote 176', 'Quote 176: <+Chaosx> I want your dad');
    this.responses.set('!quote 177', 'Quote 177: <@POKE-JJ> fuck off Sillyyy |');
    this.responses.set('!quote 178', 'Quote 178: [14:34] <+Flammablelion> fuse how long did it take you to get shiny hooha [14:35] <@Nikolai> FUSE HAS A SHINY HOOHA');
    this.responses.set('!quote 179', 'Quote 179: <@Showerlai> Guys would you date arte <+Flammable|SS> arte HELL YA');
    this.responses.set('!quote 180', 'Quote 180: <@POKE-JJ> can we do it tomorrow Sillyyy? I`m doing hw atm | <@Sillyyy> yeah');
    this.responses.set('!quote 181', 'Quote 181: <+solus|school> dude, I met her 3 days ago <@Silly|FF13> did you stick it inside her and pee');
    this.responses.set('!quote 182', 'Quote 182: <@SillyWarfare2> fat girls are a skidmark on the udnerpants of society');
    this.responses.set('!quote 183', 'Quote 183: <@SillyWarfare2> i finish fapping and now i come back and see that you`re all talking about penis size');
    this.responses.set('!quote 184', 'Quote 184: <@poke|hiatus> CHawk|Hiatus: I AM FUCKING DOING DOIN` THAT RAG');
    this.responses.set('!quote 185', 'Quote 185: <FishEater|hw> /part and /quit are on a boat. /part leaves, who`s left? <fuse> Cena');
    this.responses.set('!quote 186', 'Quote 186: <@SillyMania> furries are blow humans!');
    this.responses.set('!quote 187', 'Quote 187: <+Flammablelion> POKE how big is arte`s forehead in person/ | <@POKE> normal sized');
    this.responses.set('!quote 188', 'Quote 188: <inv4der>i love runescape!');
    this.responses.set('!quote 189', 'Quote 189: `@FiveStarJah i kinda felt bad`` for you`` but`` only for a minute`` then your old lady sucked the shitt`` of my dick`` i wasent suprised` when she told me`` that you get mad`` when she wont stick her finger in your ass`` your a fucking freak``and stay the fuck away from my apartement`` ill fucking k**ll ya``` you butt fucking wigger``');
    this.responses.set('!quote 190', 'Quote 190: <fuse>you going to bang the queen now? <Silly|wheeee>right after your dad');
    this.responses.set('!quote 191', 'Quote 191: <@POKE-JJ> i have no taste in music, enjoy counting money and watching puke porn');
    this.responses.set('!quote 192', 'Quote 192: <+fuse> in closing, i love the dick');
    this.responses.set('!quote 193', 'Quote 193: <fuse> UNBAN ME YOU FUCKING TRIPLE FUCKING DOUBLE FUCKING SINGLE FUCKING QUADRUPLE FUCKING INFINITE NIGGER');
    this.responses.set('!quote 194', 'Quote 194: <+fuse> I don`t start any argument');
    this.responses.set('!quote 195', 'Quote 195: <fuse> I state an opinion, people bitch');
    this.responses.set('!quote 196', 'Quote 196: (23:07:47) <+fuse> I`m mentally retarded.');
    this.responses.set('!quote 197', 'Quote 197: <+fuse> !gcheese|* +bdown gets 0 slices of bread and 0 slices of cheese.');
    this.responses.set('!quote 198', 'Quote 198: <@POKE-JJ> I will be nice');
    this.responses.set('!quote 199', 'Quote 199: solus|PHIV|T15|7of7 rapes artes butt');
    this.responses.set('!quote 200', 'Quote 200: <Angels2002> a vote for wyatt is a vote for JUSTICE');
    this.responses.set('!quote 201', 'Quote 201: [01:27:26] * @Pic-a-nic basket');
    this.responses.set('!quote 202', 'Quote 202: (08:50:06 pm) <+stewo> btbam sucks');
    this.responses.set('!quote 203', 'Quote 203: <@Nikolai> I HAAAAAAAAAAAAAAATE YOU JEFFFFFFF MANGUUUUUUUUM');
    this.responses.set('!quote 204', 'Quote 204: <@arte> i miss wyatt!!!');
    this.responses.set('!quote 205', 'Quote 205: <@POKE-JJ> I love you Jesus Christ !!!!!');
    this.responses.set('!quote 206', 'Quote 206: [21:09] <+Flammablelion> GOD DAMN IT THEY CURED MY DISEASE');
    this.responses.set('!quote 207', 'Quote 207: Kyle: `Everynight, I just stay up in bed, craving dick�h');
    this.responses.set('!quote 208', 'Quote 208: * +JODisBack_ np: Godsmack - Cryin` Like a Bitch [04:13m/169kbps/44kHz] | <@Sillyyy> sounds like scorehero`s theme song');
    this.responses.set('!quote 209', 'Quote 209: <@inv4der> Nik, I told you 7 OMBs in a day was easy | <@Nikolai|OurTruthOMBFC> inv4der I told you to blow me | <@inv4der> >__>');
    this.responses.set('!quote 210', 'Quote 210: <@arte> bang her <@Sillyyy> boyfriend <@Sillyyy> ... not a problem');
    this.responses.set('!quote 211', 'Quote 211: `I`m sorry inv4der, but i just couldn`t help myself. Please don`t kill me!! :(` - Vineboy');
    this.responses.set('!quote 212', 'Quote 212: [01:38] <@POKE-JJ> jesus christ');
    this.responses.set('!quote 213', 'Quote 213: (01:39:44 am) <+Lim_Fao> I HAVE A SQUARE HEAD AND FUSE IS SEXY');
    this.responses.set('!quote 214', 'Quote 214: <+sboner8790> who`s jeff mangum');
    this.responses.set('!quote 215', 'Quote 215: <@Silly|CSS> i`m an excellent fisherman <@Silly|CSS> you could say i was a... <@Silly|CSS> master baiter * @Silly|CSS puts on sunglasses <@IdiotServ> YYYYEEEEEEEEEEEAAAAAAAAAAAHHHHHHHHHHH!!!!!!!!!!!!');
    this.responses.set('!quote 216', 'Quote 216: <+BillieJoeIsBack|VoxFGFC> who cares about crackers (JODIsBack)');
    this.responses.set('!quote 217', 'Quote 217: [01:52] <+pteroid> i`m going to come to grand forks and cum in your taco');
    this.responses.set('!quote 218', 'Quote 218: <@SillyScape> i would choose video games over sex every day of the week.');
    this.responses.set('!quote 219', 'Quote 219: [2:14pm] Silly|CSS: tu est un nigger double');
    this.responses.set('!quote 220', 'Quote 220: <@LasFas> HOW`D HE DO THAT <@LasFas> HE`S GONNA FC IT TOMORROW <@LasFas> QUOTE ME ... LasFas, on some kid FCing Here We Stand on TTFAF.');
    this.responses.set('!quote 221', 'Quote 221: <@inv4der> I wonder if Mr. Jacques counts as an indie artist | <@SuperPaperNikolai> Does he suck at life? | <@inv4der> Nik, he certainly does not | <@SuperPaperNikolai> Then he most likely isn`t an indie artist.');
    this.responses.set('!quote 222', 'Quote 222: <@Nik> Goddamn Vixenita sounds like a wounded elephant when she sings. <@Sillyyy> id still put my penis inside her');
    this.responses.set('!quote 223', 'Quote 223: <+pteroid> anyone want to fuck with a 10 year old');
    this.responses.set('!quote 224', 'Quote 224: [18:49:58] * @Fugitive can`t believe he dry humped his sister');
    this.responses.set('!quote 225', 'Quote 225: <+Pieman> I hate taking a dump <+Pieman> I took one today <+Pieman> I wiped for 10 solid minutes <+Pieman> wiping black shit off my ass <+Pieman> it was that thick that it was just black <+Pieman> and it smelled <+Pieman> fuck taking a shit <@POKE-JJ> what the fuck... <+louster200> O.o <@Nikolai> Pieman <@Nikolai> might want to get that checked out.');
    this.responses.set('!quote 226', 'Quote 226: <@silly|food> omg <@silly|food> hot chick downstairs just texted me asking if i wanna come round to smoke some dope <@silly|food> siiiiik * silly|food is now known as silly|shower');
    this.responses.set('!quote 227', 'Quote 227: <+Blehgopie|MaybeStuff> !9ball yes? <+BDown> Blehgopie|MaybeStuff: 0,12As I see it, yes');
    this.responses.set('!quote 228', 'Quote 228: Kyle: GAME ROBBY CROSED?! HORRY SHIT!!');
    this.responses.set('!quote 229', 'Quote 229: (16:30:20) <@Sillyyy> i got a new african girlfriend today (16:30:35) <@Sillyyy> i discovered if i wrote `vuvuzela` on my dick she could blow it for 90 minutes');
    this.responses.set('!quote 230', 'Quote 230: <@Silly|lolthrasher> OMFG <@Silly|lolthrasher> ITS ON PAL 60 SOMEONE FUCKING KILL ME');
    this.responses.set('!quote 231', 'Quote 231: (12:17:52) <+Yewb|RS> i hope you don`t enjoy your lunch. i hope you accidentally forget to add the sauce until it`s just a little bit too late, and spend the meal thinking `this is really nice, sure, but it could be a little nicer still`.');
    this.responses.set('!quote 232', 'Quote 232: (07:09:23 pm) <+H2O^FoG> Does anyone know if it`s possible to get a GHWT Wii drum module | (07:09:34 pm) <+pteroid> probably');
    this.responses.set('!quote 233', 'Quote 233: [6:35pm] LasFas: http://lasfas.com/sounds/LoopSong.mp3 [6:36pm] Pieman: it`s loopsong three times [6:36pm] LasFas: Pieman #1 Counter [6:42pm] Pieman: HOLY SHIT LASFAS IT DOES SAY IT 4 TIMES');
    this.responses.set('!quote 234', 'Quote 234: <@ManfredvonKarma> What would seal this is if you had a picture of you, your mom, and Stan Lee');
    this.responses.set('!quote 235', 'Quote 235: <@POKE-JJ> Don`t you hate it when you`re going after a girl for like 2 months and then you find out she has a bf? ...... <@Sillyyy> no i just split them up ...... <@Sillyyy> just cuz there`s a goalie doesn`t mean you can`t score');
    this.responses.set('!quote 236', 'Quote 236: (Talking about POKE-JJ) <@Sillyyy> I WILL GET AT LEAST ONE DOLLAR OUT OF HIM BEFORE I DIE <+pteroid> he`ll pay for half of your tombstone <+pteroid> just to fuck with you');
    this.responses.set('!quote 237', 'Quote 237: <@Nikolai> L');
    this.responses.set('!quote 238', 'Quote 238: <@Feesh|tvtropes> fuse fucks furries furiously');
    this.responses.set('!quote 239', 'Quote 239: <+JODisBack> Nikolai: so you know about the digiornos pizza i was talking about the other day <@Nikolai> yeah? <+JODisBack> i didnt finish it and put it in the fridge... how long should i warm it up <+erkle82> ... <@arte> LOL');
    this.responses.set('!quote 240', 'Quote 240: <@Sillyyy> sorry erk we only accept people who own gaming consoles <@Sillyyy> not toasters with LEDs');
    this.responses.set('!quote 241', 'Quote 241: [on Rhapsody`s Power of the Dragonflame] <@silly|tired> that song is as metal as a transforemers orgy at a slayer gig');
    this.responses.set('!quote 242', 'Quote 242: [02:54:16pm] 4[Wyatt|4] WHY DOES THE WORLD HATE ME');
    this.responses.set('!quote 243', 'Quote 243: <@arte> i helped my uncle jack off a horse yesterday');
    this.responses.set('!quote 244', 'Quote 244: <@arte> i love scat');
    this.responses.set('!quote 245', 'Quote 245: [01:52:43] <@Nikolai> I had to figure masturbating out myself.');
    this.responses.set('!quote 246', 'Quote 246: <erkle82> ooh now i`m gay');
    this.responses.set('!quote 247', 'Quote 247: no #bannerhero quote here, but http://pastebin.com/TgAatk5B for fucking epic win');
    this.responses.set('!quote 248', 'Quote 248: <erkle82> this guy from fucking British Columbia says he wants to have cyber sex with me because I said I was 20 and a female XD ... <@POKE-JJ> I wasn`t on omegle');
    this.responses.set('!quote 249', 'Quote 249: <@arte> my vagina');
    this.responses.set('!quote 250', 'Quote 250: <+fuse> ill kick your ass in magic BITCH');
    this.responses.set('!quote 251', 'Quote 251: * this1neguy (~chatzilla@adsl-99-157-140-49.dsl.sfldmi.sbcglobal.net) has joined #bannerhero <+pteroid> instant fucking boner oh my god');
    this.responses.set('!quote 252', 'Quote 252: <@inv4der> two months from now, Congress passes a draft <@inv4der> 3 months from now, canada officially becomes part of the US');
    this.responses.set('!quote 253', 'Quote 253: <@Nikolai> I just made my Jim Beam/Coke around 3/4 Jim D: <+BDown> *<Nikolai> I just made a man`s beverage <+BDown> fixed it for you');
    this.responses.set('!quote 254', 'Quote 254: <@POKE-JJ> �� CHRIST IS MY SAVIOUR ��');
    this.responses.set('!quote 255', 'Quote 255: <@inv4der> Erkle is actually Meff Jangum`s son, based on the fact that Erkle`s dad also loves Jesus');
    this.responses.set('!quote 256', 'Quote 256: LasFas|WaitingforFishEater is now known as Titanic | Lim_Fao is now known as Iceberg | * @Titanic (~Seithseal@nv-71-49-169-102.dhcp.embarqhsd.net) Quit (Excess Flood)');
    this.responses.set('!quote 257', 'Quote 257: <@LunchEater> I`ll see your [10 dollars], and raise you MY FUCKING HOUSE.');
    this.responses.set('!quote 258', 'Quote 258: <@ManfredvonKarma> I do not rape dogs <@ManfredvonKarma> Cats are better <+JODisBack> dogs >>>>>>>>>>>>>>>>>>>>> cats');
    this.responses.set('!quote 259', 'Quote 259: <+bjw> FishEater was playing with his dogs balls this one day and suddenly he realized `my god, my dick has never been harder, and neither has my dogs`!` | [13:46:27] <@FishEater> Yeah, basically.');
    this.responses.set('!quote 260', 'Quote 260: <+Yewb> i heard sucking dick has a side project | <+Yewb> it`s called fuse');
    this.responses.set('!quote 261', 'Quote 261: <@ManfredvonKarma> But yeah, if you see a mediafire for Barely Legal, link me, Fish');
    this.responses.set('!quote 262', 'Quote 262: <+Pieman> I regard males and females as things I put on a pedestal <+Pieman> like trophies in brawl');
    this.responses.set('!quote 263', 'Quote 263: <@Nikolai|Class> Pieman I would break you in half. <+Pieman> sounds hot Nik');
    this.responses.set('!quote 264', 'Quote 264: <Lim_Fao> is a drop c the same thing as a c flat');
    this.responses.set('!quote 265', 'Quote 265: <Lim_Fao> it goes into F## i think');
    this.responses.set('!quote 266', 'Quote 266: [02:03:53am] 4[Nikolai4] This girl is like 4`11",  85 pounds ... I can`t wait for her to sit on my dick and just spin.');
    this.responses.set('!quote 267', 'Quote 267: [00:57:00] <+Lim_Fao> ok well im gonna play mw2 for a little');
    this.responses.set('!quote 268', 'Quote 268: <+erkle82|HAUWSE> dunno who A Perfect Circle is | <+Blehgopie|MaybeStuff> the opposite of stewo`s head');
    this.responses.set('!quote 269', 'Quote 269: <+fuse> silly i went to newbury comics yesterday and they had NMH on vinyl!! <@Silly|TheBlackRiver|OMBFC> what was newbury comics doing in your bedroom?!');
    this.responses.set('!quote 270', 'Quote 270: <@Silly`> im a better girl');
    this.responses.set('!quote 271', 'Quote 271: <+Flammablelion> CHawk did you find master cheif in the game <+Lim_Fao> someone needs to go to school more and stop playing halo <+Lim_Fao> Flammablelion, i believe its `cheif`');
    this.responses.set('!quote 272', 'Quote 272: <+Silly> I particularly enjoy fuses genetalia');
    this.responses.set('!quote 273', 'Quote 273: <@arte> then after that i use my ass vibrator for like 5 hours | <+Flammablelion> FUCK YEA I ALREADY GOT MY PANTS OFF');
    this.responses.set('!quote 274', 'Quote 274: [15:02] <+Shado> And stop yiffing my ass, damnit!');
    this.responses.set('!quote 275', 'Quote 275: <@arte> am i a furry if i find this hot <@arte> http://himichu.deviantart.com/art/Doodle-Trance-Mikoto-131779531 | +CHawk|CantSleep pushes arte over to the furry side <+CHawk|CantSleep> Nice knowing ya, bud <@arte> FUCK');
    this.responses.set('!quote 276', 'Quote 276: <+fuse> welcome to the black parade was supposed to be fun on drums? <@poke-JJ> WHEN I WAS <@poke-JJ> A YOUNG BOY <+JODNeverWasBack> no <+JODNeverWasBack> shut up <@inv4der> I PLAYED THE SILVER BALL');
    this.responses.set('!quote 277', 'Quote 277: <@arte> `girls are like multiplication tables, if they`re under 13 you should only do them in your head`');
    this.responses.set('!quote 278', 'Quote 278: <@poke-jj> guys I am so non-conformist I like brokencyde xDDDDDDDDDDDDDDDDD');
    this.responses.set('!quote 279', 'Quote 279: `I`ve been playing Rock Band since GH1` - kevinsano');
    this.responses.set('!quote 280', 'Quote 280: <+Yewb|hangover> ffx2 can fuck my shit ass gay fag homo poowank');
    this.responses.set('!quote 281', 'Quote 281: <+TL> I shoved a flute up my ass');
    this.responses.set('!quote 282', 'Quote 282: <+Lim_Fao> as a woman i take offense to that');
    this.responses.set('!quote 283', 'Quote 283: <+shooter[durnk]> i`ll `whank` you');
    this.responses.set('!quote 284', 'Quote 284: <+shooter[durnk]> well http://sphotos.ak.fbcdn.net/hphotos-ak-snc4/hs109.snc4/35802_132643886759000_100000401690858_228723_6231943_n.jpg girl on left <+shooter[durnk]> she got fucking ugly since my 11th grade year');
    this.responses.set('!quote 285', 'Quote 285: <shooter[dunno]> my favorite artist is brokenCYDE');
    this.responses.set('!quote 286', 'Quote 286: <@Silly`RB3> gonna entice my mum');
    this.responses.set('!quote 287', 'Quote 287: <@ManfredvonKarma> I thought we voted that fuse had to do the furry initiation <+fuse> ok!');
    this.responses.set('!quote 288', 'Quote 288: <@arte> spy fox was my shit (23:21:20) <@arte> ..this probably isn`t going to help the furry accusations too much');
    this.responses.set('!quote 289', 'Quote 289: (11:50:49) <+JODisBack> they could have only 15 good songs and that`d be more than DT');
    this.responses.set('!quote 290', 'Quote 290: (18:53:03) <@silly`hi> i wonder how long it will be until jack becomes so massive he collapses into himself like a neutron star');
    this.responses.set('!quote 291', 'Quote 291: Otend: I`d come up with a long post, but Pieman said what we are all thinking, as usual.');
    this.responses.set('!quote 292', 'Quote 292: http://tinyurl.com/CountryThread1 http://tinyurl.com/CountryThread2 http://tinyurl.com/CountryThread3 http://tinyurl.com/2fk6sbj (page 4) http://tinyurl.com/CountryThread5');
    this.responses.set('!quote 293', 'Quote 293: (01:45:17) <@FishEater> But it failed anyway, so it matters every less now.');
    this.responses.set('!quote 294', 'Quote 294: (23:13:02) <+Flammablelion> I did that was last year when i was retarded (23:13:11) <+TL> you mean you aren`t anymore?');
    this.responses.set('!quote 295', 'Quote 295: <+Flammablelion> I just want 13th prestige and all stuff dont want to work for stuff');
    this.responses.set('!quote 296', 'Quote 296: <@FishEater> LET THE ANTIBODIES ANTIBODIES ANTIBODIES ANTIBODIES HIT THE VISIONS OF WHAT MIGHT`VE BEEN AND WHAT WILL NEVER BEEP BEEP M` BEEP BEEP YYYYEEEEEEEEEEEAAAAAAAAAAAHHHHHHHHHHH!!!!!!!!!!!!');
    this.responses.set('!quote 297', 'Quote 297: (00:46:07) <+RAWR> ive had sex with 21 yr olds. (00:46:20) <@Pimpin`McKickAss> i`ve had sex with twenty one-year-olds.');
    this.responses.set('!quote 298', 'Quote 298: (01:03:43) <@Pimpin`McKickAss> amy winehouse has a fantastic voice its just a shame shes a methhead with a face like a horse');
    this.responses.set('!quote 299', 'Quote 299: <@poke`essayfest`2k10> solus finally figured out to stop eating <@poke`essayfest`2k10> and eat her instead <@Pimpin`McScape> na he is just dating the trix rabbit now');
    this.responses.set('!quote 300', 'Quote 300: <+Pieman> silly rabbit <+Pieman> dicks are for kids');
    this.responses.set('!quote 301', 'Quote 301: Pieman:        I am the 300th quote');
    this.responses.set('!quote 302', 'Quote 302: (17:43:09) <+Flammablelion> i cant tell if my dog shit in my room or if it was me');
    this.responses.set('!quote 303', 'Quote 303: a??`I hate poor people. Why can`t they just get money?` - Sam Jaffe.');
    this.responses.set('!quote 304', 'Quote 304: <@Pimpin`McKickAss> all i want to do is pock');
    this.responses.set('!quote 305', 'Quote 305: <@pock> FishEater what is the furry irc server plz');
    this.responses.set('!quote 306', 'Quote 306: * +Cyberwaste must grab Nikolai`s dick and bend it like a straw <+Cyberwaste> ...I want to :3');
    this.responses.set('!quote 307', 'Quote 307: <@poke> fuck your mom`s ass <+yksi-kaksi-kolme> ok');
    this.responses.set('!quote 308', 'Quote 308: <+Angels2002> hey u dang woodchucks <+Angels2002> stop chuckin mah wood! <@Smugleaf|HW> did the littlest piggy say lelele all the way home, pangels');
    this.responses.set('!quote 309', 'Quote 309: http://img217.imageshack.us/img217/5397/stewoislol.png');
    this.responses.set('!quote 310', 'Quote 310: <+yksi-kaksi-kolme> im king gaybad');
    this.responses.set('!quote 311', 'Quote 311: <@poke`cramfest`2k10> i love the taste of meat in my mouth');
    this.responses.set('!quote 312', 'Quote 312: <+Pieman> Julian I do believe it is well within my great and comprehensive understanding that the number of years you have existed on this solar rock formation in which we inhabit belongs to the groups of real numbers, integers, and whole numbers, and is exactly equal to the number nine in base ten, with a degree of accuracy within a few months of the present time.');
    this.responses.set('!quote 313', 'Quote 313: <@Silly> women are like monopoly property <@Silly> no-one wants the brown ones');
    this.responses.set('!quote 314', 'Quote 314: Trololol (in order): http://bit.ly/ihAhVS | http://bit.ly/fKBHED | http://bit.ly/fcgSfw | http://bit.ly/i8tXH6 | http://bit.ly/dFoWqP | http://bit.ly/gED4yM | http://bit.ly/hMppTl | http://bit.ly/hGKYX9 | http://bit.ly/g67ZgP | http://bit.ly/fIjQhT | http://bit.ly/hM9zsT');
    this.responses.set('!quote 315', 'Quote 315: <@CHawksCreedBrotherhood> Pieman is like a little brother to me :> <+Pieman> the kind of little brother you`d experiment awkwardly with at age 12 and then never mention it again? because that is alright');
    this.responses.set('!quote 316', 'Quote 316: *RichardGHP joins #bannerhero <+fuse> party is over forever');
    this.responses.set('!quote 317', 'Quote 317: (17:19:31) <+solrac> don`t make me turn this car around (17:19:44) <@FishEater[GH6]> A lawnmower is not a car, solrac.');
    this.responses.set('!quote 318', 'Quote 318: (17:23:38) <@inv4der> I can`t let you do that Car Fox');
    this.responses.set('!quote 319', 'Quote 319: (19:51:52) <@silly`> i am not surprised (19:51:58) <@silly`> that as soon as food is mentioned (19:52:02) <@silly`> every american in the channel is active');
    this.responses.set('!quote 320', 'Quote 320: <+smokyprogg> riz should come back, read that thread and take action accordingly <@CHawk> *Matt should come back and ban everybody ever <@sid> *JC should nuke the servers and never pay the hosting fee again');
    this.responses.set('!quote 321', 'Quote 321: (01:48:07) <@pock> arte quote me one more time and I`ll punch you');
    this.responses.set('!quote 322', 'Quote 322: Music you have in common includes abingdon boys school, A\s\E\ea Rin Toshite Shigure, TeddyLoid and Young Breezy and Ryles the Great. | <@inv4der> all of those have asian connections!');
    this.responses.set('!quote 323', 'Quote 323: fuse');
    this.responses.set('!quote 324', 'Quote 324: (13:42:02) <+shooter> I want to be a bi');
    this.responses.set('!quote 325', 'Quote 325: <+shooter> I want to be a bi-winner');
    this.responses.set('!quote 326', 'Quote 326: <+this1neguy> better drink my own piss.');
    this.responses.set('!quote 327', 'Quote 327: <@Silly> !addquote <+this1neguy> better drink my own piss.');
    this.responses.set('!quote 328', 'Quote 328: <@this1neguy> I LIKE DICKS IN THE ANUS');
    this.responses.set('!quote 329', 'Quote 329: <+shooter`> Nick Bowlin <+shooter`> i love penis');
    this.responses.set('!quote 330', 'Quote 330: (14:39:16) <Dango> ddddc can ddddie though');
    this.responses.set('!quote 331', 'Quote 331: <@Nikolai> The cure for cancer wasn`t found by laziness.');
    this.responses.set('!quote 332', 'Quote 332: (12:51:20 am) <+toymachine> there will never be Slash era GnR in Rock Band');
    this.responses.set('!quote 333', 'Quote 333: [00:23] <+gerg> !8 MAH DICK IS SOOOOO BIG ... [00:23] <@ChanServ> gerg: Not on your life.');
    this.responses.set('!quote 334', 'Quote 334: [00:25] <+louster200> !8 I ASKED YOU IF I SHOULD GO TO FUCKING BED. NOW, SHOULD I OR SHOULD I NOT? ... [00:25] <@ChanServ> louster200: Are you mad?! ... [00:25] <@Nikolai> lolololo ... [00:25] <+louster200> !8 ARE YOU FUCKING MAD ... [00:25] <@ChanServ> louster200: Yes.');
    this.responses.set('!quote 335', 'Quote 335: <+this1neguy> Hi Blaine <+Altruit> fuuuucking sucks');
    this.responses.set('!quote 336', 'Quote 336: "Thanks to strikebowler for being NTSC." -inv4der');
    this.responses.set('!quote 337', 'Quote 337: 08:54 <sid> guess i`m getting hardened again');
    this.responses.set('!quote 338', 'Quote 338: <+yksi> how do i unignore aaron <+this1neguy> ignore -r [nick]');
    this.responses.set('!quote 339', 'Quote 339: * Pieman takes a shot');
    this.responses.set('!quote 340', 'Quote 340: worse channel');
    this.responses.set('!quote 341', 'Quote 341: better channel');
    this.responses.set('!quote 342', 'Quote 342: <+fuse> WolfServ: Are you my friend? <+WolfServ> yes <+WolfServ> wait! i mean no');
    this.responses.set('!quote 343', 'Quote 343: <+Paimun> wait I typed 1c oops <+WolfServ> You`re doing it wrong. <@Silly> owned');
    this.responses.set('!quote 344', 'Quote 344: <+shtr|LETSGOPENS> i suck');
    this.responses.set('!quote 345', 'Quote 345: <+this1neguy> so assuming it works and all i`ll be able to record at the latest sometime mid-next week <@poke> aaron will be xjewz');
    this.responses.set('!quote 346', 'Quote 346: #bannerhero circlejerk http://bit.ly/xShRvH | http://bit.ly/xmP6Yf | http://bit.ly/yoyAUP');
    this.responses.set('!quote 347', 'Quote 347: <@poke> I refuse to associate with bronies <@FoshOtter> welp; <@FoshOtter> /ignore pock');
    this.responses.set('!quote 348', 'Quote 348: [16:45:59] * @FoshOtter (~Fosh@FishEater.barks.gamesurge) Quit (Quit: I shall return eventually. Maybe.) [16:46:23] * LKratos (mibbit@ip98-166-236-249.hr.hr.cox.net) has joined #bannerhero [16:47:04] <LKratos> is fish here');
    this.responses.set('!quote 349', 'Quote 349: <+this1neguy> you are mad');
    this.responses.set('!quote 350', 'Quote 350: <+Paimun> who wants to know what kind of porn I just hit the jo to ... <@sidhw> midget amputee traps');
    this.responses.set('!quote 351', 'Quote 351: * +shooter np: Toby Keith - Red Solo Cup (from Clancy`s Tavern) <@Nikolai> !kb shooter NO');
    this.responses.set('!quote 352', 'Quote 352: <TQSG> I used to slaughter chickens on my grandfather`s farm back when I lived in Mexico.');
    this.responses.set('!quote 353', 'Quote 353: <+yksi> you are right pieman');
    this.responses.set('!quote 354', 'Quote 354: <@TQSG> I`ve been listening to nothing for the past 20 minutes thinking that it was a silent section in a Godspeed song.');
    this.responses.set('!quote 355', 'Quote 355: iHomer: rather that than the fucking black lady sittin on the toilet in a bunch of my vids');
    this.responses.set('!quote 356', 'Quote 356: [04:04] <BongOfDestiny> how do these get assigned?');
    this.responses.set('!quote 357', 'Quote 357: [19:18:14] <flammablelion> i dont know if i want to go to college');
    this.responses.set('!quote 358', 'Quote 358: [23:05:17] ( flammabledrunk) now there is gator aids all over my dick');
    this.responses.set('!quote 359', 'Quote 359: [02:23:25] (+ yksi) nigga nigga nigga nigga nigga nigga nigga');
    this.responses.set('!quote 360', 'Quote 360: [21:55:26] <+yksi> hi im yksi and im a big queer');
    this.responses.set('!quote 361', 'Quote 361: [01:51:01] <@bjw> `which distro is ur waifu?`');
    this.responses.set('!quote 362', 'Quote 362: <GregoryZero> I AM THE BIGGEST WEEABOO');
    this.responses.set('!quote 363', 'Quote 363: [19:14:02] <[]> I JUST KICKED MYSELF IN THE BALLS SO HARD');
    this.responses.set('!quote 364', 'Quote 364: [22:56:16] @GregoryZero: time to pirate sixty dollars worth of software and see how well it works');
    this.responses.set('!quote 365', 'Quote 365: (+ shooter) i went outside to take my trash out, and my nipples froze.');
    this.responses.set('!quote 366', 'Quote 366: [20:24:19] @IdiotServ: The best 2hu is none of them!');
    this.responses.set('!quote 367', 'Quote 367: <this1neguy> ok i`m tired of trying to wade through their idiocy to discuss this with you');
    this.responses.set('!quote 368', 'Quote 368: [21:21:35] xcd: tp is dad');
    this.responses.set('!quote 369', 'Quote 369: oppression of the palestinians is apparently kind of tasty - otend 2014');
    this.responses.set('!quote 370', 'Quote 370: <@Silly> i used to use rb mic for pc...i hung it from the light fixture in my bedroom and had it dangling in front of my face');
    this.responses.set('!quote 371', 'Quote 371: <+MPR> what even is mono/stereo i dont know shit about that');
    this.responses.set('!quote 372', 'Quote 372: <Jellycatz> I`ll stop');
    this.responses.set('!quote 373', 'Quote 373: <Jellycatz> I`ll try later');
    this.responses.set('!quote 374', 'Quote 374: <IdiotServ> Jellycatz: The best 2hu isn`t Ran Yakumo!');
    this.responses.set('!quote 375', 'Quote 375: <otend> i think i should update that: oppression of the palestinians leads to a very bad and borderline inexplicable aftertaste like two hours later');
    this.responses.set('!quote 376', 'Quote 376: <@IdiotServ> zane: The best 2hu is birb!');
    this.responses.set('!quote 377', 'Quote 377: <@silly> aaron is the toymachine of discord');
    this.responses.set('!quote 378', 'Quote 378: <@silly> dude if i wanted to hang ouyt with autists in my own secret club i just come to this cahnnel');
    this.responses.set('!quote 379', 'Quote 379: <AmyWolf> is this saul the same actor as in breaking benjamin?');
  }

  message(from, to, text) {
    const reply = this.responses.get(text.toLowerCase());
    if (reply) {
      log(`${from} ${reply} reply`);
      this.send(to, reply);
    }
  }

  help(from) {
    this.client.notice(from, `Reply automatically responds to certain phrases.`);
  }
}
