import debug from 'debug';
import { Command } from './command.js';

const log = debug(`Random`);

export class Random extends Command {
  constructor(client) {
    super(client);

    this.responses = [
		'I have hiccups at the moment... so be back in an hour. - Salamence20',
		'EA is hiding this, they are pretending like they don`t know what I am talking about. This is completly redundant... - Salamence20',
		'sorry for acting all noobish, but whats so hard about a song about cherries? - Salamence20, on Cherry Bomb',
		'How about Coheed and Cambria OMB - Salamence20',
		'HMX ruins songs. - Salamence20',
		'HAHAHA Talkies r easy I got a 100 on Testify. Just say the wurds - VOCKSNUB, on Alive (Live)`s broken talky',
		'Is there any plans for Dream Theater DLC If they Say Yes: I will eat a tea bag If they say no: I hate them - Salamence20 on someone meeting HMX',
		'WIIIIILSOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOON! - solrac',
		'Inv4der is a sexy beast - Erkle',
		'[21:51] <+Wyatt> SHUT UP NO ONE LIKES YOU',
		'<+arte> bye semenlance',
		'[21:55] <+Angels2002> HAVE YOU CAUGHT PICKACHU YET????????',
		'<+Salamence20> !Ruels',
		'<+POKE|windupFAIL> inv4der Salamence20 is sexually aroused by 300x40 images',
		'<+SteroidPirate> Canola oil is actually rapeseed oil...',
		'<+POKE-JJ> I`m gonna take trogdor into PS and experiment with him',
		'This just might be the best OMB album out there` - 82erkle on Texas Flood',
		'I would FC all of these songs but i`m listening to music on my laptop.` - Lefty on Iron Maiden Bass',
		'Could I use my DLC from my wii to my 360?` - Some retard',
		'MY GENERATION MEDIUM BASS FC MOTHA FUCKAS` - erkle82',
		'<+Navy|Unplugged> don`t think you were here when my sister screwed me',
		'F.C.P.R.E.M.I.X. (Would remind me of something like Last Resort)` - Salamence20',
		'no, I`d say that erkle82 is multiple dicks` - inv4der',
		'<+sonicdude164|fbwoo> ill go do cows',
		'Ur moms a fuckin noob! Blink r 1 of the best bands ever u son of a dick! Go eat crap!` - some retard on youtube',
		'<Fretz> I like a nice teabag every so often',
		'[02:49am] 4[Carungimon4] I GOLTS A COBBLE BADGE MOTHER FUCKAS',
		'Jesus has finally got on the wii` - Salamence20',
		'<@ChanServ> ManfredvonKarma: Meow, I`m a cat!',
		'War ensable.... Whats so hard about that song` - Salamence20',
		'Don`t devoice me, bro!` - Arte',
		'More Ideas: YMB VoxBassTar (Kinda Like the SWW Banner)',
		'Ok, he`s gone. Add more quotes.` - DanSoup',
		'<HungrySanta> I don`t quote myself, which also, in turn, means I don`t want to be quoted',
		'Hungry HungrySanta|Hungry is Hungry, apparently` - inv4der',
		'I was playing around with it in #BAWhero one day` - inv4der',
		'naa, lets get octarium` - semenlance on Dream Theater DLC',
		'Sala20|FuckPepsi: 1 Salabyte = Infinty, never runs out',
		'I reported, expect a band soon` - Salamence20',
		'IdiotServ is back! Yay!` - inv4der',
		'where is idiotserv baww',
		'who cares about the other songs, they`re been FCd` -arte',
		'So... HungrySanta is Hungry? who would`ve guessed?` - inv4der',
		'I am really about that...` - pizzzapizza',
		'<arte> i imagine paul mccartney screaming at some kid about how it`s theirs and his birthday',
		'<fuse> omfg Yur0wn is my favorite person in the world. I`d love to meet up with him and have buttsecks sometime.',
		'To play this disc, put it in an Xbox 360 console` - arte`s 360, on having RB2 inserted',
		'<NvayCherub> !7ball So now we can have make-up sex?',
		'<+Carungi> flammable, your like 14 your dick doesnt even work yet',
		'<Drunkolai> also not gonna get any pussy tonight bevcause my pussy isn`t answering her phone',
		'* Flammablelion is now known as Fagboylion',
		'<vix> its sad when the rapist gets away because no one believes the girl | <vix> this is not that far from that situation` - Vix on e-drama',
		'<POKE-JJ> leave me alone, I`m watching porn',
		'<TeamPOKE-JJ> dog of bag poo?',
		'<dcuk> i have an arte fetish obv.',
		'(in response to being asked why he was sad) <Silly|sad> yewb`s shitty pc just screwed me over and i died on runescape',
		'<JoeTheAncientOne> CRASHING THROUGH THE BOUNDARIES LUNACY HAS FOUND ME. MY CAMERA`S OUT OF BATTERY.',
		'<HungrySanta> Invisalign officially does NOT count for the earning of the Killer Queen Day of Braces FC banner.',
		'Yes, it does.` - FishEater, on quote 58',
		'<+fusebot> NvayCherub must NvayCherub NvayCherub!',
		'<louster200> AKA: I`m a desperate 12 year old',
		'<@inv4der> you can play with me arte',
		'(in response to being asked why he was happy) <Silly|happy> because yewb`s shitty pc didn`t screw me over and I didn`t die on runescape',
		'Actually, if you think about it, It is Matt and Evan`s fault.` - Vickseeneetuhh on stuff.',
		'[17:26] <robbyx4595> ok, if i FC Rock Band Beatles on drums I will fly out to Wisconsin and lick erkle`s weiner.',
		'StephenAtHomeobama wants to kill old people. so does arthritis. so by the transitive property, oh god, obama is arthritis',
		'i know all about fantasy stuff, just not football` - arte',
		'<Silly> FUCK YOU INAVD3R U R A FOLL',
		'<+`Silly> hey guys 69 is a funny number becuas eit is also a sexual position lol!',
		'<TheLonging> .!addquote HungrySanta is a whore',
		'<@Silly> HOLY JESUS TITTYFUCKING WHAT THE GODDAMN HOLY SHIT',
		'<@SillyScape> we`re just all japanese schoolgirls',
		'<Nikolai> bannerhero, i pose a question to you:',
		'<Carungi> no i will not touch your sack',
		'<+Carungi> so i named all the handymen in my game angels2002',
		'THABEAST721> oh no my water slide got stuck',
		'<+Carungi> this guy thought `this park is really celan and tidy` and then threw up',
		'<louster200|GHSH|XGtr> I WANNA COCK!',
		'<cdylan13> At I`ve cream trucks',
		'<erkle82|PushItOMBFC> HOW WOULD YOU KNOW I LIKE COCK?!',
		'<robbyx4595> erkle, how big is your penis',
		'<POKE-JJ>: erkle82|PushItOMBFC, more like erkle82|analOMBFC',
		'<ManfredvonKarma> Figures that erkle would rather have a location on SH about licking ass than a real location',
		'<Flammablelion> POKE-JJ: What kind of anal butt cream do you use',
		'<erkle82> im a homo who loves anal cream',
		'Dick fuck cockels` - SteroidPirate',
		'<@ManfredvonKarma> Yeah, you know I love me some all male incest',
		'<NvayCherub> My mom is hotter than your mom',
		'<SpoonMan> i cant stop jizzing',
		'<@inv4der> I could indeed song it though',
		'<@ChanServ> FishEater: Are you mad?! <@FishEater> Sounds like a no.` - ChanServ on if Salvatore will ever FC Rude Mood.',
		'<Salvatore|Sunburn> !8ball Give me a girlfriend. <@ChanServ> Salvatore|Sunburn: Absolutely not.',
		'<FuckingOwnt> Psh, arte doesn`t have any friends.',
		'<RingoStarr> I`VE GOT BLISTERS ON MAH FINGAS',
		'<@HMX^IdiotServ> RIP was tracked by special guest Chris Vance',
		'<NvayCherub> it`s hilarious to FUCK YOUR MOM',
		'<robbyx4595> i wish to be the little girl',
		'I AM A HELPFUL HAMSTER` - inv4der',
		'* @ManfredvonKarma goes off to work his job a Microsoft',
		'Because I LOVE YOU [ManfredvonKarma]` - NvayCherub coming out of the closet',
		'<@FishServ> !7 Will ManfredvonKarma be alone forever? <@IdiotServ> FishServ: Seems likely.',
		'[03:00:30pm] 4[Salvatore|Sunburn4] !7ball Am I a cool guy?',
		'(>`_`)># at first i had a waffle #<(`_`<) i was gonna give it to you (>`#`<) but then i got hungry (>`-`<) so i ated it',
		'`I can pee, therefore, my dick works.` - Salvatore|BURP',
		'<Yur0wn> HEY GUYS I HAVE A VAGINA',
		'<@PhishEater> !7 Sex with ChanServ? <@IdiotServ> PhishEater: Ask me later, I`m having sex with ChanServ at the moment.',
		'[05:50] <@ahelpfulhamster> Fish, it said `hylianhero or w.e fails she `banned` me 4 mispelling words but she 4got about the register btn nd nao ill keep making thes O ND SUM CAPS 2 PISS OF THT WHORE kthxbai`',
		'that`s not my job MvK` - ahelpfulhamster, being unhelpful',
		'<S1ckH4nds> So hopefully I don`t sound like a bag of dicks for the rest of my life.',
		'[07:21:51pm] 4[S1ckH4nds|Laptop4] Those chords are charted properly, and I`m a bag of dicks.',
		'I think butt3rz just likes my style is all. - 82erkle',
		'<@Prong1978> Well fuse can kiss my ass!',
		'So I was gonna grind for the IRS guitar FC, but I decided that would be too taxing` - inv4der',
		'<@inv4der> quote 114 needs deleted | <@inv4der> because it sucks',
		'<cdylan13> does not computer',
		'<+Nikolai> now i`m sucking fuse',
		'<Angels2002> MvK reads furry comics.',
		'<+Tenfrente> My best friend, and love interest, is a girl | <Yewb> your love interest is a girl?!',
		'<simpsonfreak17|scorpion> FishEater do me now',
		'<+arteGH5> fuse likes to drop the soap',
		'I love Chris Vance` - duck|out',
		'<Flammablelion-1> I`m gonna go cry brb',
		'May I take part? I should get it first day, but if not, I`ll let you guys know. - erkle on the Beatles FGOMBFC',
		'<SteroidPirate> cockfucksuckducktruck',
		'<stewo|GR2R|FC> i had sex with fuse',
		'<@ManfredvonKarma> Just because I considered whether or not it was easier to climb a wall of erect dicks than a wall of flccid ones doesn`t mean anything',
		'...I was running around putting my face where the balls would hit it...` - ManfredvonKarma',
		'<@Silly|MockTheWeek> I got PMed about my last couple of avatard girls',
		'<@ManfredvonKarma> These nuts are good in my mouth',
		'<drifter1717> i need to drown it in vagina',
		'<+arte> everything about fuse sucks | <fuse> pretty sure a lot of people agree',
		'* @ChanServ (ChanServ@Services.GameSurge.net) Quit (oenoes!)',
		'[On Prof. Layton and the Curious Village] <JODIsBack> what could have scared the cat? who committed murder? am i playing pheonix wright or something?',
		'<robbyx4595> I HERD U LIEK METAL AND BEATLES SO I PPUT MIXELPIX IN YOUR RBB SO YOU CAN ROCK OUT WHEN YOU TROLL',
		'<@ManfredvonKarma> Cookie_Monster: I had a stuffed you when I was a child | <Cookie_Monster> did u molest me?',
		'<@Carungi> wyatt, shut up your fat ill ban you',
		'<@caRUNGIFSA> I HAVE A SMALL PENIS [repeated 15 times before exiting]',
		'<@Prong1978> Sightread FC of I`m The One on Expert Guitar!',
		'<+arte> did it with my tongue',
		'On Balloon Boy: <+POKE-JJ> stewo: HE`S BETTER THAN NJO AT TROLLING',
		'<@FishEater> I DO NOT CARE ABOUT MOUNTAIN MUD STAINS.',
		'What`s the need to inform all of us that this person is a guy not a dude?` - POKE-JJ',
		'<+bdown> If you don`t like `Penis` then fuck you',
		'<+sonicdude164> my 6 year old brother just told my mom `get the hell down here and make me a damn snack`',
		'<@Sillyyy> I gave a homeless person ��1 for a cup of tea. I wish the cunt would hurry up, I`m thirsty.',
		'<@ManfredvonKarma> I Can`t Keep My Eyes Off You is about stalking a girl named Patty | <@ManfredvonKarma> Best Day Ever is about the day when he finally rapes her',
		'<+bjw> YIFF IN HELL, MEXICO',
		'<+Angels2002> !7ball Are you a furry? | <@FishEater> Angels2002: SHUT UP YOU FUCKER!',
		'<@ManfredvonKarma> Fun fact: drifter1717 has a major erection thinking about yiffing with me, peok, and FishEater',
		'<+Angels2002> it`s like an episode of Maury, except with furries instead of fathers',
		'2* @FishOutOfWater (~LethalFis@pool-71-107-66-226.lsanca.dsl-w.verizon.net) Quit (Quit: *gasp* Can`t... breathe... out... of... water... *gasp*)',
		'<@FishEater> Rule #1: Don`t be a dick. Rule #2: Follow Rule #1. <+NvayCherub> Rule #3: No furries <@FishEater> ^',
		'<+Flammable|15LRBFCs> YOU WANT TO SEE MY DICK',
		'<+robby|LOGDAY> that means prong would have to be like 11 when he gave birth to MvK',
		'<+Flammablelion> And to get her back I stuck pizza crust up my butt',
		'<@inv4der> so IdiotServ is cured of swine cancer?',
		'<+Flammablelion> well i am a dumb ass but I am book smart',
		'<arte> i am slightly concerned that i may become a pedophile later in life',
		'<+lolus> HAHAHA I`ve been here for months and have still managed to avoid being quoted. I FUCKING WIN!',
		'<@Nikolai> Her avatar, plus the name Paintmegorgeouss <@Nikolai> would indicate female <@Nikolai> but not necessary I guess <@arte> hey remember topazgrl <@Nikolai> just ask erkle <@arte> OHHH <@inv4der> AH IRONY',
		'<+erkle82> i thinks he`s soooooooooooooooooooooo hawt',
		'<@FishEater> OH CAR A DINGO GET IN THE :U',
		'<@Prong1978|KaraokeRev_820of1000> You know what? fuse is right.',
		'[00:49] <@arte> dude i could have used the stem cells to grow my other testicle back',
		'* POKE-JJ is now known as peeeeeeeeeeeeeeeeeeeeeeeeeeeee',
		'<+CHawk> Give me a sec duck and I`ll play with you',
		'<@Silly|GH5> the sense of accomplishment you get from beating it is sooooo fucking good',
		',  Massachusetts, AH AH AH of Furefure of Massachusetts, Massachusetts, this state Gaingain, Oh, and RO RO state, the state of Lara.',
		'doobers - `I have one question for you,how do you get the rectangle club accomplishment things that you have.`',
		'<+Flammablelion> Angels2002 we must bust',
		'<+Flammablelion> STOP ADDING MY MOM ON FB',
		'<+Angels2002> funny fuse fucks furries furiously',
		'<Otend1> Same here, except replace months with a couple weeks.',
		'(10:51:57 pm) <+Angels2002> i played rb drums in front of my mom and she told me to get a life',
		'<Flammablelion> my brother took my computer and read all of mIRC and he saw that i said you were cute',
		'<+Chaosx> I want your dad',
		'<@POKE-JJ> fuck off Sillyyy |',
		'[14:34] <+Flammablelion> fuse how long did it take you to get shiny hooha [14:35] <@Nikolai> FUSE HAS A SHINY HOOHA',
		'<@Showerlai> Guys would you date arte <+Flammable|SS> arte HELL YA',
		'<@POKE-JJ> can we do it tomorrow Sillyyy? I`m doing hw atm | <@Sillyyy> yeah',
		'<+solus|school> dude, I met her 3 days ago <@Silly|FF13> did you stick it inside her and pee',
		'<@SillyWarfare2> fat girls are a skidmark on the udnerpants of society',
		'<@SillyWarfare2> i finish fapping and now i come back and see that you`re all talking about penis size',
		'<@poke|hiatus> CHawk|Hiatus: I AM FUCKING DOING DOIN` THAT RAG',
		'<FishEater|hw> /part and /quit are on a boat. /part leaves, who`s left? <fuse> Cena',
		'<@SillyMania> furries are blow humans!',
		'<+Flammablelion> POKE how big is arte`s forehead in person/ | <@POKE> normal sized',
		'<inv4der>i love runescape!',
		'`@FiveStarJah i kinda felt bad`` for you`` but`` only for a minute`` then your old lady sucked the shitt`` of my dick`` i wasent suprised` when she told me`` that you get mad`` when she wont stick her finger in your ass`` your a fucking freak``and stay the fuck away from my apartement`` ill fucking k**ll ya``` you butt fucking wigger``',
		'<fuse>you going to bang the queen now? <Silly|wheeee>right after your dad',
		'<@POKE-JJ> i have no taste in music, enjoy counting money and watching puke porn',
		'<+fuse> in closing, i love the dick',
		'<fuse> UNBAN ME YOU FUCKING TRIPLE FUCKING DOUBLE FUCKING SINGLE FUCKING QUADRUPLE FUCKING INFINITE NIGGER',
		'<+fuse> I don`t start any argument',
		'<fuse> I state an opinion, people bitch',
		'(23:07:47) <+fuse> I`m mentally retarded.',
		'<+fuse> !gcheese|* +bdown gets 0 slices of bread and 0 slices of cheese.',
		'<@POKE-JJ> I will be nice',
		'solus|PHIV|T15|7of7 rapes artes butt',
		'<Angels2002> a vote for wyatt is a vote for JUSTICE',
		'[01:27:26] * @Pic-a-nic basket',
		'(08:50:06 pm) <+stewo> btbam sucks',
		'<@Nikolai> I HAAAAAAAAAAAAAAATE YOU JEFFFFFFF MANGUUUUUUUUM',
		'<@arte> i miss wyatt!!!',
		'<@POKE-JJ> I love you Jesus Christ !!!!!',
		'[21:09] <+Flammablelion> GOD DAMN IT THEY CURED MY DISEASE',
		'Kyle: `Everynight, I just stay up in bed, craving dick�h',
		'* +JODisBack_ np: Godsmack - Cryin` Like a Bitch [04:13m/169kbps/44kHz] | <@Sillyyy> sounds like scorehero`s theme song',
		'<@inv4der> Nik, I told you 7 OMBs in a day was easy | <@Nikolai|OurTruthOMBFC> inv4der I told you to blow me | <@inv4der> >__>',
		'<@arte> bang her <@Sillyyy> boyfriend <@Sillyyy> ... not a problem',
		'`I`m sorry inv4der, but i just couldn`t help myself. Please don`t kill me!! :(` - Vineboy',
		'[01:38] <@POKE-JJ> jesus christ',
		'(01:39:44 am) <+Lim_Fao> I HAVE A SQUARE HEAD AND FUSE IS SEXY',
		'<+sboner8790> who`s jeff mangum',
		'<@Silly|CSS> i`m an excellent fisherman <@Silly|CSS> you could say i was a... <@Silly|CSS> master baiter * @Silly|CSS puts on sunglasses <@IdiotServ> YYYYEEEEEEEEEEEAAAAAAAAAAAHHHHHHHHHHH!!!!!!!!!!!!',
		'<+BillieJoeIsBack|VoxFGFC> who cares about crackers (JODIsBack)',
		'[01:52] <+pteroid> i`m going to come to grand forks and cum in your taco',
		'<@SillyScape> i would choose video games over sex every day of the week.',
		'[2:14pm] Silly|CSS: tu est un nigger double',
		'<@LasFas> HOW`D HE DO THAT <@LasFas> HE`S GONNA FC IT TOMORROW <@LasFas> QUOTE ME ... LasFas, on some kid FCing Here We Stand on TTFAF.',
		'<@inv4der> I wonder if Mr. Jacques counts as an indie artist | <@SuperPaperNikolai> Does he suck at life? | <@inv4der> Nik, he certainly does not | <@SuperPaperNikolai> Then he most likely isn`t an indie artist.',
		'<@Nik> Goddamn Vixenita sounds like a wounded elephant when she sings. <@Sillyyy> id still put my penis inside her',
		'<+pteroid> anyone want to fuck with a 10 year old',
		'[18:49:58] * @Fugitive can`t believe he dry humped his sister',
		'<+Pieman> I hate taking a dump <+Pieman> I took one today <+Pieman> I wiped for 10 solid minutes <+Pieman> wiping black shit off my ass <+Pieman> it was that thick that it was just black <+Pieman> and it smelled <+Pieman> fuck taking a shit <@POKE-JJ> what the fuck... <+louster200> O.o <@Nikolai> Pieman <@Nikolai> might want to get that checked out.',
		'<@silly|food> omg <@silly|food> hot chick downstairs just texted me asking if i wanna come round to smoke some dope <@silly|food> siiiiik * silly|food is now known as silly|shower',
		'<+Blehgopie|MaybeStuff> !9ball yes? <+BDown> Blehgopie|MaybeStuff: 0,12As I see it, yes',
		'Kyle: GAME ROBBY CROSED?! HORRY SHIT!!',
		'(16:30:20) <@Sillyyy> i got a new african girlfriend today (16:30:35) <@Sillyyy> i discovered if i wrote `vuvuzela` on my dick she could blow it for 90 minutes',
		'<@Silly|lolthrasher> OMFG <@Silly|lolthrasher> ITS ON PAL 60 SOMEONE FUCKING KILL ME',
		'(12:17:52) <+Yewb|RS> i hope you don`t enjoy your lunch. i hope you accidentally forget to add the sauce until it`s just a little bit too late, and spend the meal thinking `this is really nice, sure, but it could be a little nicer still`.',
		'(07:09:23 pm) <+H2O^FoG> Does anyone know if it`s possible to get a GHWT Wii drum module | (07:09:34 pm) <+pteroid> probably',
		'[6:35pm] LasFas: http://lasfas.com/sounds/LoopSong.mp3 [6:36pm] Pieman: it`s loopsong three times [6:36pm] LasFas: Pieman #1 Counter [6:42pm] Pieman: HOLY SHIT LASFAS IT DOES SAY IT 4 TIMES',
		'<@ManfredvonKarma> What would seal this is if you had a picture of you, your mom, and Stan Lee',
		'<@POKE-JJ> Don`t you hate it when you`re going after a girl for like 2 months and then you find out she has a bf? ...... <@Sillyyy> no i just split them up ...... <@Sillyyy> just cuz there`s a goalie doesn`t mean you can`t score',
		'(Talking about POKE-JJ) <@Sillyyy> I WILL GET AT LEAST ONE DOLLAR OUT OF HIM BEFORE I DIE <+pteroid> he`ll pay for half of your tombstone <+pteroid> just to fuck with you',
		'<@Nikolai> L',
		'<@Feesh|tvtropes> fuse fucks furries furiously',
		'<+JODisBack> Nikolai: so you know about the digiornos pizza i was talking about the other day <@Nikolai> yeah? <+JODisBack> i didnt finish it and put it in the fridge... how long should i warm it up <+erkle82> ... <@arte> LOL',
		'<@Sillyyy> sorry erk we only accept people who own gaming consoles <@Sillyyy> not toasters with LEDs',
		'[on Rhapsody`s Power of the Dragonflame] <@silly|tired> that song is as metal as a transforemers orgy at a slayer gig',
		'[02:54:16pm] 4[Wyatt|4] WHY DOES THE WORLD HATE ME',
		'<@arte> i helped my uncle jack off a horse yesterday',
		'<@arte> i love scat',
		'[01:52:43] <@Nikolai> I had to figure masturbating out myself.',
		'<erkle82> ooh now i`m gay',
		'no #bannerhero quote here, but http://pastebin.com/TgAatk5B for fucking epic win',
		'<erkle82> this guy from fucking British Columbia says he wants to have cyber sex with me because I said I was 20 and a female XD ... <@POKE-JJ> I wasn`t on omegle',
		'<@arte> my vagina',
		'<+fuse> ill kick your ass in magic BITCH',
		'* this1neguy (~chatzilla@adsl-99-157-140-49.dsl.sfldmi.sbcglobal.net) has joined #bannerhero <+pteroid> instant fucking boner oh my god',
		'<@inv4der> two months from now, Congress passes a draft <@inv4der> 3 months from now, canada officially becomes part of the US',
		'<@Nikolai> I just made my Jim Beam/Coke around 3/4 Jim D: <+BDown> *<Nikolai> I just made a man`s beverage <+BDown> fixed it for you',
		'<@POKE-JJ> �� CHRIST IS MY SAVIOUR ��',
		'<@inv4der> Erkle is actually Meff Jangum`s son, based on the fact that Erkle`s dad also loves Jesus',
		'LasFas|WaitingforFishEater is now known as Titanic | Lim_Fao is now known as Iceberg | * @Titanic (~Seithseal@nv-71-49-169-102.dhcp.embarqhsd.net) Quit (Excess Flood)',
		'<@LunchEater> I`ll see your [10 dollars], and raise you MY FUCKING HOUSE.',
		'<@ManfredvonKarma> I do not rape dogs <@ManfredvonKarma> Cats are better <+JODisBack> dogs >>>>>>>>>>>>>>>>>>>>> cats',
		'<+bjw> FishEater was playing with his dogs balls this one day and suddenly he realized `my god, my dick has never been harder, and neither has my dogs`!` | [13:46:27] <@FishEater> Yeah, basically.',
		'<+Yewb> i heard sucking dick has a side project | <+Yewb> it`s called fuse',
		'<@ManfredvonKarma> But yeah, if you see a mediafire for Barely Legal, link me, Fish',
		'<+Pieman> I regard males and females as things I put on a pedestal <+Pieman> like trophies in brawl',
		'<@Nikolai|Class> Pieman I would break you in half. <+Pieman> sounds hot Nik',
		'<Lim_Fao> is a drop c the same thing as a c flat',
		'<Lim_Fao> it goes into F## i think',
		'[02:03:53am] 4[Nikolai4] This girl is like 4`11",  85 pounds ... I can`t wait for her to sit on my dick and just spin.',
		'[00:57:00] <+Lim_Fao> ok well im gonna play mw2 for a little',
		'<+erkle82|HAUWSE> dunno who A Perfect Circle is | <+Blehgopie|MaybeStuff> the opposite of stewo`s head',
		'<+fuse> silly i went to newbury comics yesterday and they had NMH on vinyl!! <@Silly|TheBlackRiver|OMBFC> what was newbury comics doing in your bedroom?!',
		'<@Silly`> im a better girl',
		'<+Flammablelion> CHawk did you find master cheif in the game <+Lim_Fao> someone needs to go to school more and stop playing halo <+Lim_Fao> Flammablelion, i believe its `cheif`',
		'<+Silly> I particularly enjoy fuses genetalia',
		'<@arte> then after that i use my ass vibrator for like 5 hours | <+Flammablelion> FUCK YEA I ALREADY GOT MY PANTS OFF',
		'[15:02] <+Shado> And stop yiffing my ass, damnit!',
		'<@arte> am i a furry if i find this hot <@arte> http://himichu.deviantart.com/art/Doodle-Trance-Mikoto-131779531 | +CHawk|CantSleep pushes arte over to the furry side <+CHawk|CantSleep> Nice knowing ya, bud <@arte> FUCK',
		'<+fuse> welcome to the black parade was supposed to be fun on drums? <@poke-JJ> WHEN I WAS <@poke-JJ> A YOUNG BOY <+JODNeverWasBack> no <+JODNeverWasBack> shut up <@inv4der> I PLAYED THE SILVER BALL',
		'<@arte> `girls are like multiplication tables, if they`re under 13 you should only do them in your head`',
		'<@poke-jj> guys I am so non-conformist I like brokencyde xDDDDDDDDDDDDDDDDD',
		'`I`ve been playing Rock Band since GH1` - kevinsano',
		'<+Yewb|hangover> ffx2 can fuck my shit ass gay fag homo poowank',
		'<+TL> I shoved a flute up my ass',
		'<+Lim_Fao> as a woman i take offense to that',
		'<+shooter[durnk]> i`ll `whank` you',
		'<+shooter[durnk]> well http://sphotos.ak.fbcdn.net/hphotos-ak-snc4/hs109.snc4/35802_132643886759000_100000401690858_228723_6231943_n.jpg girl on left <+shooter[durnk]> she got fucking ugly since my 11th grade year',
		'<shooter[dunno]> my favorite artist is brokenCYDE',
		'<@Silly`RB3> gonna entice my mum',
		'<@ManfredvonKarma> I thought we voted that fuse had to do the furry initiation <+fuse> ok!',
		'<@arte> spy fox was my shit (23:21:20) <@arte> ..this probably isn`t going to help the furry accusations too much',
		'(11:50:49) <+JODisBack> they could have only 15 good songs and that`d be more than DT',
		'(18:53:03) <@silly`hi> i wonder how long it will be until jack becomes so massive he collapses into himself like a neutron star',
		'Otend: I`d come up with a long post, but Pieman said what we are all thinking, as usual.',
		'http://tinyurl.com/CountryThread1 http://tinyurl.com/CountryThread2 http://tinyurl.com/CountryThread3 http://tinyurl.com/2fk6sbj (page 4) http://tinyurl.com/CountryThread5',
		'(01:45:17) <@FishEater> But it failed anyway, so it matters every less now.',
		'(23:13:02) <+Flammablelion> I did that was last year when i was retarded (23:13:11) <+TL> you mean you aren`t anymore?',
		'<+Flammablelion> I just want 13th prestige and all stuff dont want to work for stuff',
		'<@FishEater> LET THE ANTIBODIES ANTIBODIES ANTIBODIES ANTIBODIES HIT THE VISIONS OF WHAT MIGHT`VE BEEN AND WHAT WILL NEVER BEEP BEEP M` BEEP BEEP YYYYEEEEEEEEEEEAAAAAAAAAAAHHHHHHHHHHH!!!!!!!!!!!!',
		'(00:46:07) <+RAWR> ive had sex with 21 yr olds. (00:46:20) <@Pimpin`McKickAss> i`ve had sex with twenty one-year-olds.',
		'(01:03:43) <@Pimpin`McKickAss> amy winehouse has a fantastic voice its just a shame shes a methhead with a face like a horse',
		'<@poke`essayfest`2k10> solus finally figured out to stop eating <@poke`essayfest`2k10> and eat her instead <@Pimpin`McScape> na he is just dating the trix rabbit now',
		'<+Pieman> silly rabbit <+Pieman> dicks are for kids',
		'Pieman:        I am the 300th quote',
		'(17:43:09) <+Flammablelion> i cant tell if my dog shit in my room or if it was me',
		'a??`I hate poor people. Why can`t they just get money?` - Sam Jaffe.',
		'<@Pimpin`McKickAss> all i want to do is pock',
		'<@pock> FishEater what is the furry irc server plz',
		'* +Cyberwaste must grab Nikolai`s dick and bend it like a straw <+Cyberwaste> ...I want to :3',
		'<@poke> fuck your mom`s ass <+yksi-kaksi-kolme> ok',
		'<+Angels2002> hey u dang woodchucks <+Angels2002> stop chuckin mah wood! <@Smugleaf|HW> did the littlest piggy say lelele all the way home, pangels',
		'http://img217.imageshack.us/img217/5397/stewoislol.png',
		'<+yksi-kaksi-kolme> im king gaybad',
		'<@poke`cramfest`2k10> i love the taste of meat in my mouth',
		'<+Pieman> Julian I do believe it is well within my great and comprehensive understanding that the number of years you have existed on this solar rock formation in which we inhabit belongs to the groups of real numbers, integers, and whole numbers, and is exactly equal to the number nine in base ten, with a degree of accuracy within a few months of the present time.',
		'<@Silly> women are like monopoly property <@Silly> no-one wants the brown ones',
		'Trololol (in order): http://bit.ly/ihAhVS | http://bit.ly/fKBHED | http://bit.ly/fcgSfw | http://bit.ly/i8tXH6 | http://bit.ly/dFoWqP | http://bit.ly/gED4yM | http://bit.ly/hMppTl | http://bit.ly/hGKYX9 | http://bit.ly/g67ZgP | http://bit.ly/fIjQhT | http://bit.ly/hM9zsT',
		'<@CHawksCreedBrotherhood> Pieman is like a little brother to me :> <+Pieman> the kind of little brother you`d experiment awkwardly with at age 12 and then never mention it again? because that is alright',
		'*RichardGHP joins #bannerhero <+fuse> party is over forever',
		'(17:19:31) <+solrac> don`t make me turn this car around (17:19:44) <@FishEater[GH6]> A lawnmower is not a car, solrac.',
		'(17:23:38) <@inv4der> I can`t let you do that Car Fox',
		'(19:51:52) <@silly`> i am not surprised (19:51:58) <@silly`> that as soon as food is mentioned (19:52:02) <@silly`> every american in the channel is active',
		'<+smokyprogg> riz should come back, read that thread and take action accordingly <@CHawk> *Matt should come back and ban everybody ever <@sid> *JC should nuke the servers and never pay the hosting fee again',
		'(01:48:07) <@pock> arte quote me one more time and I`ll punch you',
		'<@inv4der> Music you have in common includes abingdon boys school, A\s\E\ea Rin Toshite Shigure, TeddyLoid and Young Breezy and Ryles the Great. | <@inv4der> all of those have asian connections!',
		'fuse',
		'(13:42:02) <+shooter> I want to be a bi',
		'<+shooter> I want to be a bi-winner',
		'<+this1neguy> better drink my own piss.',
		'<@Silly> !addquote <+this1neguy> better drink my own piss.',
		'<@this1neguy> I LIKE DICKS IN THE ANUS',
		'<+shooter`> Nick Bowlin <+shooter`> i love penis',
		'(14:39:16) <Dango> ddddc can ddddie though',
		'<@Nikolai> The cure for cancer wasn`t found by laziness.',
		'(12:51:20 am) <+toymachine> there will never be Slash era GnR in Rock Band',
		'[00:23] <+gerg> !8 MAH DICK IS SOOOOO BIG ... [00:23] <@ChanServ> gerg: Not on your life.',
		'[00:25] <+louster200> !8 I ASKED YOU IF I SHOULD GO TO FUCKING BED. NOW, SHOULD I OR SHOULD I NOT? ... [00:25] <@ChanServ> louster200: Are you mad?! ... [00:25] <@Nikolai> lolololo ... [00:25] <+louster200> !8 ARE YOU FUCKING MAD ... [00:25] <@ChanServ> louster200: Yes.',
		'<+this1neguy> Hi Blaine <+Altruit> fuuuucking sucks',
		'"Thanks to strikebowler for being NTSC." -inv4der',
		'08:54 <sid> guess i`m getting hardened again',
		'<+yksi> how do i unignore aaron <+this1neguy> ignore -r [nick]',
		'* Pieman takes a shot',
		'worse channel',
		'better channel',
		'<+fuse> WolfServ: Are you my friend? <+WolfServ> yes <+WolfServ> wait! i mean no',
		'<+Paimun> wait I typed 1c oops <+WolfServ> You`re doing it wrong. <@Silly> owned',
		'<+shtr|LETSGOPENS> i suck',
		'<+this1neguy> so assuming it works and all i`ll be able to record at the latest sometime mid-next week <@poke> aaron will be xjewz',
		'#bannerhero circlejerk http://bit.ly/xShRvH | http://bit.ly/xmP6Yf | http://bit.ly/yoyAUP',
		'<@poke> I refuse to associate with bronies <@FoshOtter> welp; <@FoshOtter> /ignore pock',
		'[16:45:59] * @FoshOtter (~Fosh@FishEater.barks.gamesurge) Quit (Quit: I shall return eventually. Maybe.) [16:46:23] * LKratos (mibbit@ip98-166-236-249.hr.hr.cox.net) has joined #bannerhero [16:47:04] <LKratos> is fish here',
		'<+this1neguy> you are mad',
		'<+Paimun> who wants to know what kind of porn I just hit the jo to ... <@sidhw> midget amputee traps',
		'* +shooter np: Toby Keith - Red Solo Cup (from Clancy`s Tavern) <@Nikolai> !kb shooter NO',
		'<TQSG> I used to slaughter chickens on my grandfather`s farm back when I lived in Mexico.',
		'<+yksi> you are right pieman',
		'<@TQSG> I`ve been listening to nothing for the past 20 minutes thinking that it was a silent section in a Godspeed song.',
		'iHomer: rather that than the fucking black lady sittin on the toilet in a bunch of my vids',
		'[04:04] <BongOfDestiny> how do these get assigned?',
		'[19:18:14] <flammablelion> i dont know if i want to go to college',
		'[23:05:17] ( flammabledrunk) now there is gator aids all over my dick',
		'[02:23:25] (+ yksi) nigga nigga nigga nigga nigga nigga nigga',
		'[21:55:26] <+yksi> hi im yksi and im a big queer',
		'[01:51:01] <@bjw> `which distro is ur waifu?`',
		'<GregoryZero> I AM THE BIGGEST WEEABOO',
		'[19:14:02] <[]> I JUST KICKED MYSELF IN THE BALLS SO HARD',
		'[22:56:16] @GregoryZero: time to pirate sixty dollars worth of software and see how well it works',
		'(+ shooter) i went outside to take my trash out, and my nipples froze.',
		'[20:24:19] @IdiotServ: The best 2hu is none of them!',
		'<this1neguy> ok i`m tired of trying to wade through their idiocy to discuss this with you',
		'[21:21:35] xcd: tp is dad',
		'oppression of the palestinians is apparently kind of tasty - otend 2014',
		'<@Silly> i used to use rb mic for pc...i hung it from the light fixture in my bedroom and had it dangling in front of my face',
		'<+MPR> what even is mono/stereo i dont know shit about that',
		'<Jellycatz> I`ll stop',
    '<IdiotServ> Jellycatz: The best 2hu isn`t Ran Yakumo!',
    '<otend> i think i should update that: oppression of the palestinians leads to a very bad and borderline inexplicable aftertaste like two hours later',
    '<@IdiotServ> zane: The best 2hu is birb!',
    '<@silly> aaron is the toymachine of discord',
    '<@silly> dude if i wanted to hang ouyt with autists in my own secret club i just come to this cahnnel',
    '<AmyWolf> is this saul the same actor as in breaking benjamin?',
    ];
  }

  message(from, to, text) {
    if (text.startsWith(`!rando`)) {
      log(`${from} on: ${text}`);

      const result = this.responses[Math.floor(Math.random() * this.responses.length)];
      this.send(to, `${result}`);
    }
  }

  help(from) {
    this.client.notice(from, `.8ball question; randomly outputs response`);
  }
}
