import debug from 'debug';
import { Command } from './command.js';

const log = debug('Touhou');

export class Touhou extends Command {
  constructor(client) {
    super(client);

    this.responses = [
      'The best 2hu is Reimu Hakurei!',
      'The best 2hu is Shingyoku!',
      'The best 2hu is YuugenMagan!',
      'The best 2hu is Elis!',
      'The best 2hu is Sariel!',
      'The best 2hu is Kikuri!',
      'The best 2hu is Konngara!',
      'The best 2hu is Genjii!',
      'The best 2hu is Clownpiece!',
      'The best 2hu is Hecatia Lapislazuli!',
      'The best 2hu is Junko!',
      'The best 2hu is Sagume Kishin!',
      'The best 2hu is Doremy Sweet!',
      'The best 2hu is Ringo!',
      'The best 2hu is Seiran!',
      "The best 2hu is Sumireko Usami!",
      'The best 2hu is Rika!',
      'The best 2hu is Meira!',
      'The best 2hu is Marisa Kirsame!',
      'The best 2hu is Evil Eye Sigma!',
      'The best 2hu is Ellen!',
      'The best 2hu is Kotohime!',
      'The best 2hu is Kana Anaberal!',
      'The best 2hu is Rikako Asakura!',
      'The best 2hu is Chiyuri Kitashirakawa!',
      'The best 2hu is Yumemi Okazaki!',
      'The best 2hu is Ruukoto!',
      'The best 2hu is Orange!',
      'The best 2hu is Kurumi!',
      'The best 2hu is Elly!',
      'The best 2hu is Yuuka Kazami!',
      'The best 2hu is Mugetsu!',
      'The best 2hu is Gengetsu!',
      'The best 2hu is Sara!',
      'The best 2hu is Luize!',
      'The best 2hu is Alice Margatroid!',
      'The best 2hu is Yuki!',
      'The best 2hu is Mai!',
      'The best 2hu is Yumeko!',
      'The best 2hu is Shinki!',
      'The best 2hu is Rumia!',
      'The best 2hu is Daiyousei!',
      'The best 2hu is Hong Meiling!',
      'The best 2hu is Koakuma!',
      'The best 2hu isn`t Patchouli Knowledge!',
      'The best 2hu is Sakuya Izayoi!',
      'The best 2hu is Remilia Scarlet!',
      'The best 2hu is Flandre Scarlet!',
      'The best 2hu is Letty Whiterock!',
      'The best 2hu is CHEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEN!',
      'The best 2hu is Lily White!',
      'The best 2hu is Layla Prismriver!',
      'The best 2hu is Lunasa Prismriver!',
      'The best 2hu is Merlin Prismriver!',
      'The best 2hu is Lyrica Prismriver!',
      'The best 2hu is Youmu Konpaku!',
      'The best 2hu is Youki Konpaku!',
      'The best 2hu is Yuyuko Saigyouji!',
      'The best 2hu is Saigyou Ayakashi!',
      'The best 2hu isn`t Ran Yakumo!',
      'The best 2hu is Ran Yakumo!',
      'The best 2hu is Yukari Yakumo!',
      'The best 2hu is Suika Ibuki!',
      'The best 2hu is Wriggle Nightbug!',
      'The best 2hu is Mystia Lorelei!',
      'The best 2hu is birb!',
      'The best 2hu is Keine Kamishirasawa!',
      'The best 2hu is Tewi Inaba!',
      'The best 2hu is Reisen Udongein Inaba!',
      'The best 2hu is it`s pronounced Reisen not Reisen!',
      'The best 2hu is Eirin Yagokro!',
      'The best 2hu is Kaguya Houraisan!',
      'The best 2hu is Fujiwara no Mokou!',
      'The best 2hu is Aya Shameimaru!',
      'The best 2hu is Ayayayayayayayayayaya!',
      'The best 2hu is Medicine Melancholy!',
      'The best 2hu is Komachi Onozuka!',
      'The best 2hu is Eiki Shiki, Yamaxanadu!',
      'The best 2hu is Shizuha Aki!',
      'The best 2hu is Minoriko Aki!',
      'The best 2hu is Hina Kagiyama!',
      'The best 2hu is Nitori Kawashiro!',
      'The best 2hu is Momiji Inubashiri! awoo~',
      'The best 2hu is Sanae Kochiya!',
      'The best 2hu is Sanaynay!',
      'The best 2hu is Kanako Yasaka!',
      'The best 2hu is Suwako Moriya!',
      'The best 2hu is Iku Nagae!',
      'The best 2hu is Tenshi Hinanawi!',
      'The best 2hu is Kisume!',
      'The best 2hu is Yamame Kurodani!',
      'The best 2hu is Parsee Mizuhashi!',
      'The best 2hu is Yuugi Hoshiguma!',
      'The best 2hu is Satori Komeji!',
      'The best 2hu is Rin Kaenbyou!',
      'The best 2hu is Utsuho Reiuji!',
      'The best 2hu is Koishi Komeiji!',
      'The best 2hu is Nazrin!',
      'The best 2hu is Kogasa Tatara!',
      'The best 2hu is Ichirin Kumoi!',
      'The best 2hu is Unzan!',
      'The best 2hu is Kogasa Tatara!',
      'The best 2hu is Ichirin Kumoi!',
      'The best 2hu is Unzan!',
      'The best 2hu is Minamitsu Murasa!',
      'The best 2hu is Shou Toramaru!',
      'The best 2hu is Byakuren Hijiri!',
      'The best 2hu is Youkai Jesus!',
      'The best 2hu is Myouren!',
      'The best 2hu is Nue Houjuu!',
      'The best 2hu is The Catfish!',
      'The best 2hu is Hatate Himekaidou!',
      'The best 2hu is Kyouko Kasodani!',
      'The best 2hu is Yoshika Miyako!',
      'The best 2hu is Seiga Kaku!',
      'The best 2hu is Soga no Tojiko!',
      'The best 2hu is Mononobe no Futo!',
      'The best 2hu is Toyosatomimi no Miko!',
      'The best 2hu is Mamizou Futatsuiwa!',
      'The best 2hu is Hata no Kokoro!',
      'The best 2hu is Wakasagihime!',
      'The best 2hu is Sekibanki!',
      'The best 2hu is Kagerou Imaizumi!',
      'The best 2hu is Benben Tsukumo!',
      'The best 2hu is Yatsuhashi Tsukumo!',
      'The best 2hu is Seija Kijin!',
      'The best 2hu is Shinmyoumaru Sukuna!',
      'The best 2hu is Raiko Horikawa!',
      'The best 2hu is not Rinnosuke Morichika!',
      'The best 2hu is Tokiko!',
      'The best 2hu is Maribel Hearn!',
      'The best 2hu is Renko Usami!',
      'The best 2hu is Sunny Milk!',
      'The best 2hu is Luna Child!',
      'The best 2hu is Star Sapphire!',
      'The best 2hu is Heida no Akyuu!',
      'The best 2hu is Reisen II!',
      'The best 2hu is Watatsuki no Yorihime!',
      'The best 2hu is Watatsuki no Toyohime!',
      'The best 2hu is Kasen Ibaraki!',
      'The best 2hu is it`s pronounced Kasen not Kasen!',
      'The best 2hu is Kosuzu Motoori!',
      'The best 2hu is Rin Satsuki!',
      'The best 2hu is Tenma!',
      'The best 2hu is none of them!',
      'The best 2hu is all of them!',
    ];
  }

  message(from, to, text) {
    if (text.startsWith('!2h')) {
      log(`${from} on: ${text}`);

      const result = this.responses[Math.floor(Math.random() * this.responses.length)];
      this.send(to, `${from}: ${result}`);
    }
  }

  help(from) {
    this.client.notice(from, `.8ball question; randomly outputs response`);
  }
}
